/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ./public/models/3d-car-compressed.glb --keepnames 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/3d-car-compressed.glb')
  return (
    <group {...props} dispose={null}>
      <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]} scale={1.053}>
        <mesh name="body" geometry={nodes.body.geometry} material={nodes.body.material} position={[0, -0.002, 0.614]} scale={2.371} />
        <mesh name="Object_10" geometry={nodes.Object_10.geometry} material={materials.REDFRONTPLandspoilers_pl_tex5} position={[0, -0.006, 0.612]} scale={2.353} />
        <mesh name="Object_11" geometry={nodes.Object_11.geometry} material={materials.bac_tex2} position={[0, 0.393, 0.927]} scale={0.67} />
        <mesh name="Object_12" geometry={nodes.Object_12.geometry} material={nodes.Object_12.material} position={[0, 0.452, 0.324]} scale={1.834} />
        <mesh name="Object_13" geometry={nodes.Object_13.geometry} material={materials.black_chrome} position={[0, -0.022, 0.613]} scale={2.371} />
        <mesh name="Object_14" geometry={nodes.Object_14.geometry} material={nodes.Object_14.material} position={[0, -0.007, 0.591]} scale={2.371} />
        <mesh name="Object_15" geometry={nodes.Object_15.geometry} material={materials.black_plastic} position={[0, -0.015, 0.614]} scale={2.379} />
        <mesh name="Object_16" geometry={nodes.Object_16.geometry} material={materials.bolts} position={[0, 0.152, 0.339]} scale={1.475} />
        <mesh name="Object_17" geometry={nodes.Object_17.geometry} material={nodes.Object_17.material} position={[0, -0.163, 0.214]} scale={2.142} />
        <mesh name="Object_18" geometry={nodes.Object_18.geometry} material={materials.brakedisc_tex5} position={[0, 0.154, 0.341]} scale={1.579} />
        <mesh name="Object_19" geometry={nodes.Object_19.geometry} material={materials.carbon} position={[0, -0.155, 0.533]} scale={2.2} />
        <mesh name="Object_2" geometry={nodes.Object_2.geometry} material={materials.CASPITAspoiler} position={[0.018, 2.08, 0.927]} scale={0.54} />
        <mesh name="Object_20" geometry={nodes.Object_20.geometry} material={materials.chrome} position={[0, 0.175, 0.616]} scale={1.549} />
        <mesh name="Object_21" geometry={nodes.Object_21.geometry} material={materials.emb_L} position={[0.95, 0.151, 0.338]} scale={1.432} />
        <mesh name="Object_22" geometry={nodes.Object_22.geometry} material={materials.emb_R} position={[-0.95, 0.151, 0.338]} scale={1.432} />
        <mesh name="Object_23" geometry={nodes.Object_23.geometry} material={materials.grill_2} position={[0, -2.147, 0.208]} scale={0.749} />
        <mesh name="Object_24" geometry={nodes.Object_24.geometry} material={materials.grill_tex3} position={[0, 0.291, 0.871]} scale={1.809} />
        <mesh name="Object_25" geometry={nodes.Object_25.geometry} material={materials.headlight_glass} position={[0, -1.945, 0.552]} scale={0.877} />
        <mesh name="Object_26" geometry={nodes.Object_26.geometry} material={materials.headlights_tex1} position={[0, -1.852, 0.564]} scale={0.798} />
        <mesh name="Object_27" geometry={nodes.Object_27.geometry} material={materials.material} position={[0, -0.088, 0.607]} scale={1.268} />
        <mesh name="Object_28" geometry={nodes.Object_28.geometry} material={materials.intPL} position={[0.371, -0.901, 0.739]} scale={0.148} />
        <mesh name="Object_29" geometry={nodes.Object_29.geometry} material={materials.intlamp_gls_tex2} position={[0, -0.158, 1.055]} scale={0.045} />
        <mesh name="Object_3" geometry={nodes.Object_3.geometry} material={materials.JiottoCHRM_tex1} position={[0, -0.005, 0.512]} scale={2.318} />
        <mesh name="Object_30" geometry={nodes.Object_30.geometry} material={materials.keylock_tex1} position={[0.24, -0.694, 0.615]} scale={0.018} />
        <mesh name="Object_31" geometry={nodes.Object_31.geometry} material={materials.kvrrem_tex4} position={[0, -0.221, 0.532]} scale={0.695} />
        <mesh name="Object_32" geometry={nodes.Object_32.geometry} material={materials.lampBUTTON_pl_tex1} position={[0, -0.265, 1.061]} scale={0.048} />
        <mesh name="Object_33" geometry={nodes.Object_33.geometry} material={materials.keylock_tex1} position={[0, -0.266, 1.061]} scale={0.026} />
        <mesh name="Object_34" geometry={nodes.Object_34.geometry} material={materials.brakedisc_tex5} position={[-0.002, 0.015, 0.424]} scale={0.141} />
        <mesh name="Object_35" geometry={nodes.Object_35.geometry} material={materials.mirrors_tex5} position={[0, -0.487, 0.883]} scale={0.994} />
        <mesh name="Object_36" geometry={nodes.Object_36.geometry} material={materials.intlamp_gls_tex2} position={[0, -0.035, 0.275]} scale={2.358} />
        <mesh name="Object_37" geometry={nodes.Object_37.geometry} material={materials.brakedisc_tex5} position={[0, 2.286, 0.279]} scale={0.252} />
        <mesh name="Object_38" geometry={nodes.Object_38.geometry} material={materials.pchrome_tex5} position={[0, -0.006, 0.348]} scale={2.293} />
        <mesh name="Object_39" geometry={nodes.Object_39.geometry} material={materials.pexhachrome_tex5} position={[0, 0.568, 0.248]} scale={1.737} />
        <mesh name="Object_4" geometry={nodes.Object_4.geometry} material={materials.lampBUTTON_pl_tex1} position={[0, 0.607, 0.331]} scale={1.008} />
        <mesh name="Object_40" geometry={nodes.Object_40.geometry} material={materials.phole_tex5} position={[0, 2.193, 0.27]} scale={0.244} />
        <mesh name="Object_41" geometry={nodes.Object_41.geometry} material={materials.plate} position={[0, -0.038, 0.348]} scale={2.354} />
        <mesh name="Object_42" geometry={nodes.Object_42.geometry} material={materials.brakedisc_tex5} position={[0, 1.654, 0.14]} scale={0.626} />
        <mesh name="Object_43" geometry={nodes.Object_43.geometry} material={materials.ppl_tex5} position={[0, 0.218, 0.412]} scale={1.518} />
        <mesh name="Object_44" geometry={nodes.Object_44.geometry} material={materials.radiator2_tex3} position={[0, -2.135, 0.209]} scale={0.395} />
        <mesh name="Object_45" geometry={nodes.Object_45.geometry} material={materials.radiator_tex1} position={[0, -0.821, 0.406]} scale={1.34} />
        <mesh name="Object_46" geometry={nodes.Object_46.geometry} material={materials.lampBUTTON_pl_tex1} position={[-0.003, -0.791, 0.714]} scale={0.01} />
        <mesh name="Object_47" geometry={nodes.Object_47.geometry} material={materials.material_45} position={[0, 0.155, 0.343]} scale={1.652} />
        <mesh name="Object_48" geometry={nodes.Object_48.geometry} material={materials.rimins1} position={[0, 0.155, 0.342]} scale={1.623} />
        <mesh name="Object_49" geometry={nodes.Object_49.geometry} material={materials.rimins2} position={[0, 0.155, 0.34]} scale={1.605} />
        <mesh name="Object_50" geometry={nodes.Object_50.geometry} material={materials.spd_gls_tex3} position={[0.37, -0.749, 0.739]} scale={0.196} />
        <mesh name="Object_51" geometry={nodes.Object_51.geometry} material={materials.intlamp_gls_tex2} position={[0.364, -0.595, 0.705]} scale={0.212} />
        <mesh name="Object_52" geometry={nodes.Object_52.geometry} material={materials.suport_tex5} position={[0, 0.304, 0.359]} scale={1.449} />
        <mesh name="Object_53" geometry={nodes.Object_53.geometry} material={materials.lampBUTTON_pl_tex1} position={[0, 0.702, 0.515]} scale={1.622} />
        <mesh name="Object_54" geometry={nodes.Object_54.geometry} material={materials.tex1_brakelights} position={[0, 1.419, 0.781]} scale={0.948} />
        <mesh name="Object_55" geometry={nodes.Object_55.geometry} material={materials.tex2} position={[0, 0.057, 0.414]} scale={2.284} />
        <mesh name="Object_56" geometry={nodes.Object_56.geometry} material={materials.tire} position={[0, 0.157, 0.344]} scale={1.745} />
        <mesh name="Object_57" geometry={nodes.Object_57.geometry} material={materials.tire_L} position={[0.858, 0.156, 0.344]} scale={1.72} />
        <mesh name="Object_58" geometry={nodes.Object_58.geometry} material={materials.tire_R} position={[-0.858, 0.156, 0.344]} scale={1.72} />
        <mesh name="Object_59" geometry={nodes.Object_59.geometry} material={materials.voofer_tex1} position={[0, -0.694, 0.416]} scale={0.718} />
        <mesh name="Object_6" geometry={nodes.Object_6.geometry} material={materials.LOGOhoodCHRM_tex2} position={[0.001, -2.211, 0.426]} scale={0.039} />
        <mesh name="Object_60" geometry={nodes.Object_60.geometry} material={materials.material_58} position={[0, -0.61, 0.918]} scale={0.795} />
        <mesh name="Object_61" geometry={nodes.Object_61.geometry} material={materials.material_59} position={[0, 0.861, 0.944]} scale={0.659} />
        <mesh name="Object_7" geometry={nodes.Object_7.geometry} material={materials.intlamp_gls_tex2} position={[0.001, -2.211, 0.428]} scale={0.038} />
        <mesh name="Object_8" geometry={nodes.Object_8.geometry} material={materials.intlamp_gls_tex2} position={[0, -2.393, 0.131]} scale={0.191} />
        <mesh name="Object_9" geometry={nodes.Object_9.geometry} material={materials.POWEREDBYSUBARU} position={[0, 0.622, 0.162]} scale={0.979} />
      </group>
    </group>
  )
}

useGLTF.preload('/3d-car-compressed.glb')
