/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ./public/models/car.glb --keepnames -o ./src/components/car/index.tsx 
*/

import * as THREE from "three";
import { useEffect, useRef, useState, type JSX } from "react";
import { useGLTF } from "@react-three/drei";
import { type GLTF } from "three-stdlib";
import BodyMaterial from "./materials/BodyMaterial";
import { useFrame } from "@react-three/fiber";

type GLTFResult = GLTF & {
  nodes: {
    body: THREE.Mesh;
    Object_10: THREE.Mesh;
    Object_11: THREE.Mesh;
    Object_12: THREE.Mesh;
    Object_13: THREE.Mesh;
    Object_14: THREE.Mesh;
    Object_15: THREE.Mesh;
    Object_16012: THREE.Mesh;
    Object_16013: THREE.Mesh;
    Object_16014: THREE.Mesh;
    Object_16015: THREE.Mesh;
    Object_17: THREE.Mesh;
    Object_18016: THREE.Mesh;
    Object_18017: THREE.Mesh;
    Object_18018: THREE.Mesh;
    Object_18019: THREE.Mesh;
    Object_18020: THREE.Mesh;
    Object_18021: THREE.Mesh;
    Object_18022: THREE.Mesh;
    Object_18023: THREE.Mesh;
    Object_19: THREE.Mesh;
    Object_2: THREE.Mesh;
    Object_22: THREE.Mesh;
    Object_23: THREE.Mesh;
    Object_24: THREE.Mesh;
    Object_25: THREE.Mesh;
    Object_26: THREE.Mesh;
    Object_27: THREE.Mesh;
    Object_28: THREE.Mesh;
    Object_29: THREE.Mesh;
    Object_3: THREE.Mesh;
    Object_30: THREE.Mesh;
    Object_31: THREE.Mesh;
    Object_32: THREE.Mesh;
    Object_33: THREE.Mesh;
    Object_34: THREE.Mesh;
    Object_35: THREE.Mesh;
    Object_36: THREE.Mesh;
    Object_37: THREE.Mesh;
    Object_38: THREE.Mesh;
    Object_39: THREE.Mesh;
    Object_4: THREE.Mesh;
    Object_40: THREE.Mesh;
    Object_41: THREE.Mesh;
    Object_42: THREE.Mesh;
    Object_43: THREE.Mesh;
    Object_44: THREE.Mesh;
    Object_45: THREE.Mesh;
    Object_46: THREE.Mesh;
    Object_50: THREE.Mesh;
    Object_51: THREE.Mesh;
    Object_52: THREE.Mesh;
    Object_53: THREE.Mesh;
    Object_54: THREE.Mesh;
    Object_55: THREE.Mesh;
    Object_56028: THREE.Mesh;
    Object_56029: THREE.Mesh;
    Object_56030: THREE.Mesh;
    Object_56031: THREE.Mesh;
    Object_57002: THREE.Mesh;
    Object_59: THREE.Mesh;
    Object_6: THREE.Mesh;
    Object_60: THREE.Mesh;
    Object_61: THREE.Mesh;
    Object_7: THREE.Mesh;
    Object_8: THREE.Mesh;
    Object_9: THREE.Mesh;
    Object_55001: THREE.Mesh;
    Object_55001_1: THREE.Mesh;
    Object_55001_2: THREE.Mesh;
    Object_55001_3: THREE.Mesh;
    Object_55001_4: THREE.Mesh;
    Object_55001_5: THREE.Mesh;
    Object_55001_6: THREE.Mesh;
    Object_55001_7: THREE.Mesh;
    Object_55004: THREE.Mesh;
    Object_55004_1: THREE.Mesh;
    Object_55004_2: THREE.Mesh;
    Object_55004_3: THREE.Mesh;
    Object_55004_4: THREE.Mesh;
    Object_55004_5: THREE.Mesh;
    Object_55004_6: THREE.Mesh;
    Object_55004_7: THREE.Mesh;
    Object_55005: THREE.Mesh;
    Object_55005_1: THREE.Mesh;
    Object_55005_2: THREE.Mesh;
    Object_55005_3: THREE.Mesh;
    Object_55005_4: THREE.Mesh;
    Object_55005_5: THREE.Mesh;
    Object_55005_6: THREE.Mesh;
    Object_55005_7: THREE.Mesh;
    Object_55006: THREE.Mesh;
    Object_55006_1: THREE.Mesh;
    Object_55006_2: THREE.Mesh;
    Object_55006_3: THREE.Mesh;
    Object_55006_4: THREE.Mesh;
    Object_55006_5: THREE.Mesh;
    Object_55006_6: THREE.Mesh;
    Object_55006_7: THREE.Mesh;
  };
  materials: {
    REDFRONTPLandspoilers_pl_tex5: THREE.MeshStandardMaterial;
    bac_tex2: THREE.MeshStandardMaterial;
    black_chrome: THREE.MeshStandardMaterial;
    black_plastic: THREE.MeshPhysicalMaterial;
    bolts: THREE.MeshPhysicalMaterial;
    brakedisc_tex5: THREE.MeshStandardMaterial;
    carbon: THREE.MeshPhysicalMaterial;
    CASPITAspoiler: THREE.MeshStandardMaterial;
    emb_R: THREE.MeshPhysicalMaterial;
    grill_2: THREE.MeshStandardMaterial;
    grill_tex3: THREE.MeshStandardMaterial;
    headlight_glass: THREE.MeshPhysicalMaterial;
    headlights_tex1: THREE.MeshPhysicalMaterial;
    material: THREE.MeshStandardMaterial;
    intPL: THREE.MeshPhysicalMaterial;
    intlamp_gls_tex2: THREE.MeshPhysicalMaterial;
    JiottoCHRM_tex1: THREE.MeshStandardMaterial;
    keylock_tex1: THREE.MeshStandardMaterial;
    kvrrem_tex4: THREE.MeshStandardMaterial;
    lampBUTTON_pl_tex1: THREE.MeshPhysicalMaterial;
    lampBUTTON_tex1: THREE.MeshStandardMaterial;
    lockRED_tex5: THREE.MeshStandardMaterial;
    mirrors_tex5: THREE.MeshPhysicalMaterial;
    need_for_speed_tex2: THREE.MeshPhysicalMaterial;
    pbronze_tex5: THREE.MeshStandardMaterial;
    pchrome_tex5: THREE.MeshPhysicalMaterial;
    pexhachrome_tex5: THREE.MeshPhysicalMaterial;
    JiottoPL_tex1: THREE.MeshPhysicalMaterial;
    phole_tex5: THREE.MeshStandardMaterial;
    plate: THREE.MeshStandardMaterial;
    pmate_tex5: THREE.MeshStandardMaterial;
    ppl_tex5: THREE.MeshPhysicalMaterial;
    radiator2_tex3: THREE.MeshStandardMaterial;
    radiator_tex1: THREE.MeshStandardMaterial;
    redtriangle_pl_tex1: THREE.MeshPhysicalMaterial;
    spd_gls_tex3: THREE.MeshPhysicalMaterial;
    stickbuttons_pl_tex2: THREE.MeshPhysicalMaterial;
    suport_tex5: THREE.MeshPhysicalMaterial;
    tex1: THREE.MeshPhysicalMaterial;
    tex1_brakelights: THREE.MeshPhysicalMaterial;
    tex2: THREE.MeshPhysicalMaterial;
    tire: THREE.MeshStandardMaterial;
    tire_L: THREE.MeshStandardMaterial;
    voofer_tex1: THREE.MeshStandardMaterial;
    LOGOhoodCHRM_tex2: THREE.MeshPhysicalMaterial;
    material_58: THREE.MeshPhysicalMaterial;
    material_59: THREE.MeshPhysicalMaterial;
    LOGOhood_tex2: THREE.MeshPhysicalMaterial;
    PLlogo_tex2: THREE.MeshPhysicalMaterial;
    POWEREDBYSUBARU: THREE.MeshPhysicalMaterial;
    emb_L: THREE.MeshPhysicalMaterial;
    material_45: THREE.MeshPhysicalMaterial;
    rimins1: THREE.MeshPhysicalMaterial;
    rimins2: THREE.MeshPhysicalMaterial;
  };
};

const TYRE_ROTATE_SPEED = 12

export function Car(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF(
    "/models/car.glb",
  ) as unknown as GLTFResult;

  const groupRef = useRef<THREE.Group>(null);
  const tyresRef = useRef<(THREE.Group<THREE.Object3DEventMap> | null)[]>([]);
  const [bounds, setBounds] = useState({ min: 0, max: 2 });


  useEffect(() => {
    if (!groupRef.current) return;
    const box = new THREE.Box3().setFromObject(groupRef.current);
    setBounds({
      min: box.min.y,
      max: box.max.y,
    });
  }, [nodes]);

  useFrame((_,dt) => {
    tyresRef.current.forEach(Tyre => {
      if(Tyre) {
        Tyre.rotation.x += TYRE_ROTATE_SPEED * dt;
      }
    })
  });

  return (
    <group
      {...props}
      dispose={null}
      ref={(group) => {
        groupRef.current = group;
        group?.traverse((child) => {
          if (child instanceof THREE.Mesh) {
            child.castShadow = true;
            child.receiveShadow = true;
          }
        });
      }}
    >
      <group
        name="Sketchfab_model"
        rotation={[-Math.PI / 2, 0, 0]}
        scale={1.053}
      >
        <mesh
          name="body"
          geometry={nodes.body.geometry}
        >
          <BodyMaterial minY={bounds.min} maxY={bounds.max * 1.5} />
        </mesh>
        <mesh
          name="Object_10"
          geometry={nodes.Object_10.geometry}
          material={materials.REDFRONTPLandspoilers_pl_tex5}
        />
        <mesh
          name="Object_11"
          geometry={nodes.Object_11.geometry}
          material={materials.bac_tex2}
        />
        <mesh
          name="Object_12"
          geometry={nodes.Object_12.geometry}
          material={nodes.Object_12.material}
        />
        <mesh
          name="Object_13"
          geometry={nodes.Object_13.geometry}
          material={materials.black_chrome}
        />
        <mesh
          name="Object_14"
          geometry={nodes.Object_14.geometry}
          material={nodes.Object_14.material}
        />
        <mesh
          name="Object_15"
          geometry={nodes.Object_15.geometry}
          material={materials.black_plastic}
        />
        <mesh
          name="Object_16012"
          geometry={nodes.Object_16012.geometry}
          material={materials.bolts}
        />
        <mesh
          name="Object_16013"
          geometry={nodes.Object_16013.geometry}
          material={materials.bolts}
        />
        <mesh
          name="Object_16014"
          geometry={nodes.Object_16014.geometry}
          material={materials.bolts}
        />
        <mesh
          name="Object_16015"
          geometry={nodes.Object_16015.geometry}
          material={materials.bolts}
        />
        <mesh
          name="Object_17"
          geometry={nodes.Object_17.geometry}
          material={nodes.Object_17.material}
        />
        <mesh
          name="Object_18016"
          geometry={nodes.Object_18016.geometry}
          material={materials.brakedisc_tex5}
        />
        <mesh
          name="Object_18017"
          geometry={nodes.Object_18017.geometry}
          material={materials.brakedisc_tex5}
        />
        <mesh
          name="Object_18018"
          geometry={nodes.Object_18018.geometry}
          material={materials.brakedisc_tex5}
        />
        <mesh
          name="Object_18019"
          geometry={nodes.Object_18019.geometry}
          material={materials.brakedisc_tex5}
        />
        <mesh
          name="Object_18020"
          geometry={nodes.Object_18020.geometry}
          material={materials.brakedisc_tex5}
        />
        <mesh
          name="Object_18021"
          geometry={nodes.Object_18021.geometry}
          material={materials.brakedisc_tex5}
        />
        <mesh
          name="Object_18022"
          geometry={nodes.Object_18022.geometry}
          material={materials.brakedisc_tex5}
        />
        <mesh
          name="Object_18023"
          geometry={nodes.Object_18023.geometry}
          material={materials.brakedisc_tex5}
        />
        <mesh
          name="Object_19"
          geometry={nodes.Object_19.geometry}
          material={materials.carbon}
        />
        <mesh
          name="Object_2"
          geometry={nodes.Object_2.geometry}
          material={materials.CASPITAspoiler}
        />
        <mesh
          name="Object_22"
          geometry={nodes.Object_22.geometry}
          material={materials.emb_R}
        />
        <mesh
          name="Object_23"
          geometry={nodes.Object_23.geometry}
          material={materials.grill_2}
        />
        <mesh
          name="Object_24"
          geometry={nodes.Object_24.geometry}
          material={materials.grill_tex3}
        />
        <mesh
          name="Object_25"
          geometry={nodes.Object_25.geometry}
          material={materials.headlight_glass}
        />
        <mesh
          name="Object_26"
          geometry={nodes.Object_26.geometry}
          material={materials.headlights_tex1}
        />
        <mesh
          name="Object_27"
          geometry={nodes.Object_27.geometry}
          material={materials.material}
        />
        <mesh
          name="Object_28"
          geometry={nodes.Object_28.geometry}
          material={materials.intPL}
        />
        <mesh
          name="Object_29"
          geometry={nodes.Object_29.geometry}
          material={materials.intlamp_gls_tex2}
        />
        <mesh
          name="Object_3"
          geometry={nodes.Object_3.geometry}
          material={materials.JiottoCHRM_tex1}
        />
        <mesh
          name="Object_30"
          geometry={nodes.Object_30.geometry}
          material={materials.keylock_tex1}
        />
        <mesh
          name="Object_31"
          geometry={nodes.Object_31.geometry}
          material={materials.kvrrem_tex4}
        />
        <mesh
          name="Object_32"
          geometry={nodes.Object_32.geometry}
          material={materials.lampBUTTON_pl_tex1}
        />
        <mesh
          name="Object_33"
          geometry={nodes.Object_33.geometry}
          material={materials.lampBUTTON_tex1}
        />
        <mesh
          name="Object_34"
          geometry={nodes.Object_34.geometry}
          material={materials.lockRED_tex5}
        />
        <mesh
          name="Object_35"
          geometry={nodes.Object_35.geometry}
          material={materials.mirrors_tex5}
        />
        <mesh
          name="Object_36"
          geometry={nodes.Object_36.geometry}
          material={materials.need_for_speed_tex2}
        />
        <mesh
          name="Object_37"
          geometry={nodes.Object_37.geometry}
          material={materials.pbronze_tex5}
        />
        <mesh
          name="Object_38"
          geometry={nodes.Object_38.geometry}
          material={materials.pchrome_tex5}
        />
        <mesh
          name="Object_39"
          geometry={nodes.Object_39.geometry}
          material={materials.pexhachrome_tex5}
        />
        <mesh
          name="Object_4"
          geometry={nodes.Object_4.geometry}
          material={materials.JiottoPL_tex1}
        />
        <mesh
          name="Object_40"
          geometry={nodes.Object_40.geometry}
          material={materials.phole_tex5}
        />
        <mesh
          name="Object_41"
          geometry={nodes.Object_41.geometry}
          material={materials.plate}
        />
        <mesh
          name="Object_42"
          geometry={nodes.Object_42.geometry}
          material={materials.pmate_tex5}
        />
        <mesh
          name="Object_43"
          geometry={nodes.Object_43.geometry}
          material={materials.ppl_tex5}
        />
        <mesh
          name="Object_44"
          geometry={nodes.Object_44.geometry}
          material={materials.radiator2_tex3}
        />
        <mesh
          name="Object_45"
          geometry={nodes.Object_45.geometry}
          material={materials.radiator_tex1}
        />
        <mesh
          name="Object_46"
          geometry={nodes.Object_46.geometry}
          material={materials.redtriangle_pl_tex1}
        />
        <mesh
          name="Object_50"
          geometry={nodes.Object_50.geometry}
          material={materials.spd_gls_tex3}
        />
        <mesh
          name="Object_51"
          geometry={nodes.Object_51.geometry}
          material={materials.stickbuttons_pl_tex2}
        />
        <mesh
          name="Object_52"
          geometry={nodes.Object_52.geometry}
          material={materials.suport_tex5}
        />
        <mesh
          name="Object_53"
          geometry={nodes.Object_53.geometry}
          material={materials.tex1}
        />
        <mesh
          name="Object_54"
          geometry={nodes.Object_54.geometry}
          material={materials.tex1_brakelights}
        />
        <mesh
          name="Object_55"
          geometry={nodes.Object_55.geometry}
          material={materials.tex2}
        />
        <mesh
          name="Object_56028"
          geometry={nodes.Object_56028.geometry}
          material={materials.tire}
        />
        <mesh
          name="Object_56029"
          geometry={nodes.Object_56029.geometry}
          material={materials.tire}
        />
        <mesh
          name="Object_56030"
          geometry={nodes.Object_56030.geometry}
          material={materials.tire}
        />
        <mesh
          name="Object_56031"
          geometry={nodes.Object_56031.geometry}
          material={materials.tire}
        />
        <mesh
          name="Object_57002"
          geometry={nodes.Object_57002.geometry}
          material={materials.tire_L}
        />
        <mesh
          name="Object_59"
          geometry={nodes.Object_59.geometry}
          material={materials.voofer_tex1}
        />
        <mesh
          name="Object_6"
          geometry={nodes.Object_6.geometry}
          material={materials.LOGOhoodCHRM_tex2}
        />
        <mesh
          name="Object_60"
          geometry={nodes.Object_60.geometry}
          material={materials.material_58}
        />
        <mesh
          name="Object_61"
          geometry={nodes.Object_61.geometry}
          material={materials.material_59}
        />
        <mesh
          name="Object_7"
          geometry={nodes.Object_7.geometry}
          material={materials.LOGOhood_tex2}
        />
        <mesh
          name="Object_8"
          geometry={nodes.Object_8.geometry}
          material={materials.PLlogo_tex2}
        />
        <mesh
          name="Object_9"
          geometry={nodes.Object_9.geometry}
          material={materials.POWEREDBYSUBARU}
        />
        <group
          ref={(el) => (tyresRef.current[0] = el)}
          name="tyre-1"
          position={[0.963, -1.254, 0.331]}
        >
          <mesh
            name="Object_55001"
            geometry={nodes.Object_55001.geometry}
            material={materials.tire_L}
          />
          <mesh
            name="Object_55001_1"
            geometry={nodes.Object_55001_1.geometry}
            material={materials.bolts}
          />
          <mesh
            name="Object_55001_2"
            geometry={nodes.Object_55001_2.geometry}
            material={materials.brakedisc_tex5}
          />
          <mesh
            name="Object_55001_3"
            geometry={nodes.Object_55001_3.geometry}
            material={materials.emb_L}
          />
          <mesh
            name="Object_55001_4"
            geometry={nodes.Object_55001_4.geometry}
            material={materials.material_45}
          />
          <mesh
            name="Object_55001_5"
            geometry={nodes.Object_55001_5.geometry}
            material={materials.rimins1}
          />
          <mesh
            name="Object_55001_6"
            geometry={nodes.Object_55001_6.geometry}
            material={materials.rimins2}
          />
          <mesh
            name="Object_55001_7"
            geometry={nodes.Object_55001_7.geometry}
            material={materials.tire}
          />
        </group>
        <group
          ref={(el) => (tyresRef.current[1] = el)}
          name="tyre-2"
          position={[0.916, 1.554, 0.344]}
        >
          <mesh
            name="Object_55004"
            geometry={nodes.Object_55004.geometry}
            material={materials.tire_L}
          />
          <mesh
            name="Object_55004_1"
            geometry={nodes.Object_55004_1.geometry}
            material={materials.bolts}
          />
          <mesh
            name="Object_55004_2"
            geometry={nodes.Object_55004_2.geometry}
            material={materials.brakedisc_tex5}
          />
          <mesh
            name="Object_55004_3"
            geometry={nodes.Object_55004_3.geometry}
            material={materials.emb_L}
          />
          <mesh
            name="Object_55004_4"
            geometry={nodes.Object_55004_4.geometry}
            material={materials.material_45}
          />
          <mesh
            name="Object_55004_5"
            geometry={nodes.Object_55004_5.geometry}
            material={materials.rimins1}
          />
          <mesh
            name="Object_55004_6"
            geometry={nodes.Object_55004_6.geometry}
            material={materials.rimins2}
          />
          <mesh
            name="Object_55004_7"
            geometry={nodes.Object_55004_7.geometry}
            material={materials.tire}
          />
        </group>
        <group
          ref={(el) => (tyresRef.current[2] = el)}
          name="tyre-3"
          position={[-0.963, -1.254, 0.331]}
          rotation={[0, 0, -Math.PI]}
        >
          <mesh
            name="Object_55005"
            geometry={nodes.Object_55005.geometry}
            material={materials.tire_L}
          />
          <mesh
            name="Object_55005_1"
            geometry={nodes.Object_55005_1.geometry}
            material={materials.bolts}
          />
          <mesh
            name="Object_55005_2"
            geometry={nodes.Object_55005_2.geometry}
            material={materials.brakedisc_tex5}
          />
          <mesh
            name="Object_55005_3"
            geometry={nodes.Object_55005_3.geometry}
            material={materials.emb_L}
          />
          <mesh
            name="Object_55005_4"
            geometry={nodes.Object_55005_4.geometry}
            material={materials.material_45}
          />
          <mesh
            name="Object_55005_5"
            geometry={nodes.Object_55005_5.geometry}
            material={materials.rimins1}
          />
          <mesh
            name="Object_55005_6"
            geometry={nodes.Object_55005_6.geometry}
            material={materials.rimins2}
          />
          <mesh
            name="Object_55005_7"
            geometry={nodes.Object_55005_7.geometry}
            material={materials.tire}
          />
        </group>
        <group
          ref={(el) => (tyresRef.current[3] = el)}
          name="tyre-4"
          position={[-0.916, 1.554, 0.344]}
          rotation={[0, 0, -Math.PI]}
        >
          <mesh
            name="Object_55006"
            geometry={nodes.Object_55006.geometry}
            material={materials.tire_L}
          />
          <mesh
            name="Object_55006_1"
            geometry={nodes.Object_55006_1.geometry}
            material={materials.bolts}
          />
          <mesh
            name="Object_55006_2"
            geometry={nodes.Object_55006_2.geometry}
            material={materials.brakedisc_tex5}
          />
          <mesh
            name="Object_55006_3"
            geometry={nodes.Object_55006_3.geometry}
            material={materials.emb_L}
          />
          <mesh
            name="Object_55006_4"
            geometry={nodes.Object_55006_4.geometry}
            material={materials.material_45}
          />
          <mesh
            name="Object_55006_5"
            geometry={nodes.Object_55006_5.geometry}
            material={materials.rimins1}
          />
          <mesh
            name="Object_55006_6"
            geometry={nodes.Object_55006_6.geometry}
            material={materials.rimins2}
          />
          <mesh
            name="Object_55006_7"
            geometry={nodes.Object_55006_7.geometry}
            material={materials.tire}
          />
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/models/car.glb");
