/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ./public/models/cybercar-compressed.glb --keepnames -o ./src/components/cybercar/index.tsx 
*/

import * as THREE from "three";
import { type JSX } from "react";
import { useGLTF } from "@react-three/drei";
import { type GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    car_0: THREE.Mesh;
    car001_0: THREE.Mesh;
    car001_1: THREE.Mesh;
    car002_0: THREE.Mesh;
    car003_0: THREE.Mesh;
    car004_0: THREE.Mesh;
    car005_0: THREE.Mesh;
    car005_1: THREE.Mesh;
    car006_0: THREE.Mesh;
    car007_0: THREE.Mesh;
    car007_1: THREE.Mesh;
    car007_2: THREE.Mesh;
    car008_0: THREE.Mesh;
    car009_0: THREE.Mesh;
    car011_0: THREE.Mesh;
    car013_0: THREE.Mesh;
    car014_0: THREE.Mesh;
    car014_1: THREE.Mesh;
    car014_2: THREE.Mesh;
    car015_0: THREE.Mesh;
    car016_0: THREE.Mesh;
    car017_0: THREE.Mesh;
    car018_0: THREE.Mesh;
    car018_1: THREE.Mesh;
    car019_0: THREE.Mesh;
    car019_1: THREE.Mesh;
    Cube000_0: THREE.Mesh;
    Cube001_0: THREE.Mesh;
    Cube002_0: THREE.Mesh;
    Cube003_0: THREE.Mesh;
    Cube004_0: THREE.Mesh;
    ["boost-trail"]: THREE.Mesh;
    Cube005_0: THREE.Mesh;
    Cube005_0003: THREE.Mesh;
    Cube006_0: THREE.Mesh;
    Cube007_0: THREE.Mesh;
    Cube008_0: THREE.Mesh;
    Cube009_0: THREE.Mesh;
    Cube010_0: THREE.Mesh;
    Cube011_0: THREE.Mesh;
    Cube013_0: THREE.Mesh;
    Cylinder_0: THREE.Mesh;
    Cylinder005_0: THREE.Mesh;
    Cylinder001_0: THREE.Mesh;
    Cylinder001_1: THREE.Mesh;
    Cylinder001_2: THREE.Mesh;
    Cylinder001_3: THREE.Mesh;
    Cylinder002_0: THREE.Mesh;
    Cylinder003_0: THREE.Mesh;
    Cylinder006_0: THREE.Mesh;
    Cylinder006_1: THREE.Mesh;
    Cylinder006_2: THREE.Mesh;
    Cylinder006_3: THREE.Mesh;
    Cylinder006_4: THREE.Mesh;
    Cylinder007_0: THREE.Mesh;
    Torus001_0: THREE.Mesh;
    Torus001_0_1: THREE.Mesh;
    Cylinder010_0: THREE.Mesh;
    Cylinder009_0: THREE.Mesh;
    Cylinder011_0: THREE.Mesh;
    Torus000_0: THREE.Mesh;
    Torus000_0_1: THREE.Mesh;
    Cylinder004_0: THREE.Mesh;
    Cylinder004_1: THREE.Mesh;
    Cylinder012_0: THREE.Mesh;
    Cylinder013_0: THREE.Mesh;
    Cylinder013_1: THREE.Mesh;
    Cylinder013_2: THREE.Mesh;
    Cylinder014_0: THREE.Mesh;
    Cylinder014_1: THREE.Mesh;
    Cylinder014_2: THREE.Mesh;
    Cylinder014_3: THREE.Mesh;
    Cylinder016_0: THREE.Mesh;
    Cylinder015_0: THREE.Mesh;
    Cylinder015_1: THREE.Mesh;
    Cylinder015_2: THREE.Mesh;
    Cylinder015_3: THREE.Mesh;
    Cylinder017_0: THREE.Mesh;
    Cylinder019_0: THREE.Mesh;
    Cylinder019_1: THREE.Mesh;
    Cylinder019_2: THREE.Mesh;
    Cylinder018_0: THREE.Mesh;
    Cylinder020_0: THREE.Mesh;
    Torus002_1: THREE.Mesh;
    Torus002_1_1: THREE.Mesh;
    Cylinder022_0: THREE.Mesh;
    Cylinder022_1: THREE.Mesh;
    Cylinder021_0: THREE.Mesh;
    Cylinder023_0: THREE.Mesh;
    Cylinder024_0: THREE.Mesh;
    Cylinder024_1: THREE.Mesh;
    Cylinder024_2: THREE.Mesh;
    Cylinder024_3: THREE.Mesh;
    Cylinder024_4: THREE.Mesh;
    Cylinder025_0: THREE.Mesh;
    Cylinder027_0: THREE.Mesh;
    Cylinder026_0: THREE.Mesh;
    Cylinder026_1: THREE.Mesh;
    Cylinder026_2: THREE.Mesh;
    Cylinder026_3: THREE.Mesh;
    Cylinder026_4: THREE.Mesh;
    Cylinder028_0: THREE.Mesh;
    Plane_0: THREE.Mesh;
    Plane001_0: THREE.Mesh;
    Plane002_0: THREE.Mesh;
    Plane002_1: THREE.Mesh;
    Plane002_2: THREE.Mesh;
    Plane002_3: THREE.Mesh;
    Plane003_0: THREE.Mesh;
    Plane004_0: THREE.Mesh;
    Plane004_1: THREE.Mesh;
    Plane004_2: THREE.Mesh;
    Plane004_3: THREE.Mesh;
    Plane006_0: THREE.Mesh;
    Plane007_0: THREE.Mesh;
    Plane008_0: THREE.Mesh;
    Plane009_0: THREE.Mesh;
    Plane010_0: THREE.Mesh;
    Plane011_0: THREE.Mesh;
    Plane012_0: THREE.Mesh;
    Plane013_0: THREE.Mesh;
    Plane014_0: THREE.Mesh;
    Plane015_0: THREE.Mesh;
    Plane016_0: THREE.Mesh;
    Plane017_0: THREE.Mesh;
    Plane018_0: THREE.Mesh;
    Plane019_0: THREE.Mesh;
  };
  materials: {
    cdp_metal: THREE.MeshStandardMaterial;
    cdp_body: THREE.MeshStandardMaterial;
    gloss: THREE.MeshStandardMaterial;
    white_light: THREE.MeshStandardMaterial;
    cdp_plastic: THREE.MeshStandardMaterial;
    thruster: THREE.MeshStandardMaterial;
  };
};

export function Cybercar(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF(
    "/models/cybercar-compressed.glb",
  ) as unknown as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <group name="model_pivot" position={[0, 1.085, 0]}>
        <group
          name="Sketchfab_model"
          position={[0, -0.409, 0]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={0.208}
        >
          <group name="car007" position={[-1.979, 0, 0]}>
            <mesh
              name="car007_0"
              geometry={nodes.car007_0.geometry}
              material={materials.cdp_metal}
              position={[-3.1, 5.812, 1.714]}
              scale={1.57}
            />
            <mesh
              name="car007_1"
              geometry={nodes.car007_1.geometry}
              material={materials.white_light}
              position={[-4.631, 5.806, 1.719]}
              scale={0.32}
            />
            <mesh
              name="car007_2"
              geometry={nodes.car007_2.geometry}
              material={materials.cdp_plastic}
              position={[-4.215, 5.822, 1.697]}
              scale={0.639}
            />
          </group>
          <group name="car014" position={[1.979, 0, 0]}>
            <mesh
              name="car014_0"
              geometry={nodes.car014_0.geometry}
              material={materials.cdp_metal}
              position={[3.1, 5.812, 1.714]}
              scale={1.57}
            />
            <mesh
              name="car014_1"
              geometry={nodes.car014_1.geometry}
              material={materials.white_light}
              position={[4.631, 5.806, 1.719]}
              scale={0.32}
            />
            <mesh
              name="car014_2"
              geometry={nodes.car014_2.geometry}
              material={materials.cdp_plastic}
              position={[4.215, 5.822, 1.697]}
              scale={0.639}
            />
          </group>
          <group name="car018" position={[0, 6.49, 6.724]}>
            <mesh
              name="car018_0"
              geometry={nodes.car018_0.geometry}
              material={materials.cdp_body}
              position={[0, 2.848, -0.186]}
              scale={2.886}
            />
            <mesh
              name="car018_1"
              geometry={nodes.car018_1.geometry}
              material={materials.gloss}
              position={[0, 2.848, -0.179]}
              scale={2.894}
            />
          </group>
          <group
            name="Cube001"
            position={[2.812, -6.537, 0.418]}
            rotation={[0, 0, -1.553]}
            scale={0.919}
          >
            <mesh
              name="Cube001_0"
              geometry={nodes.Cube001_0.geometry}
              material={materials.cdp_metal}
              position={[-1.125, -3.037, -0.061]}
              scale={3.691}
            />
          </group>
          <group name="Cube005" position={[1.458, 14.952, 3.951]}>
            <mesh
              name="boost-trail"
              geometry={nodes["boost-trail"].geometry}
              material={materials.cdp_metal}
              position={[-1.458, 14.07, 1.125]}
              scale={12.647}
            />
            <mesh
              name="Cube005_0"
              geometry={nodes.Cube005_0.geometry}
              material={materials.cdp_metal}
              position={[-1.458, -1.936, 0.498]}
              scale={4.131}
            />
            <mesh
              name="Cube005_0003"
              geometry={nodes.Cube005_0003.geometry}
              material={materials.cdp_metal}
              position={[-1.458, -1.936, 0.498]}
              scale={4.131}
            />
          </group>
          <group
            name="Cube006"
            position={[2.812, -6.537, 0.418]}
            rotation={[0, 0, -1.553]}
            scale={0.919}
          >
            <mesh
              name="Cube006_0"
              geometry={nodes.Cube006_0.geometry}
              material={materials.cdp_plastic}
              position={[-1.091, -3.046, -0.038]}
              scale={3.514}
            />
          </group>
          <group
            name="Cube007"
            position={[1.458, 14.952, 3.951]}
            rotation={[0.066, 0, 0.005]}
            scale={[1.009, 1.09, 1.009]}
          >
            <mesh
              name="Cube007_0"
              geometry={nodes.Cube007_0.geometry}
              material={materials.cdp_plastic}
              position={[-1.438, 1.596, 0.977]}
              scale={2.135}
            />
          </group>
          <group
            name="Cube010"
            position={[5.638, 0.672, 3.939]}
            rotation={[0.062, 0.041, -0.035]}
            scale={[0.896, 1.767, 0.799]}
          >
            <mesh
              name="Cube010_0"
              geometry={nodes.Cube010_0.geometry}
              material={materials.white_light}
              position={[-6.307, -0.048, -0.088]}
              scale={7.27}
            />
          </group>
          <group
            name="Cube011"
            position={[1.458, 14.952, 3.951]}
            rotation={[0.066, 0, 0.005]}
            scale={[1.009, 1.09, 1.009]}
          >
            <mesh
              name="Cube011_0"
              geometry={nodes.Cube011_0.geometry}
              material={materials.thruster}
              position={[-1.438, 1.558, 0.984]}
              scale={2.129}
            />
          </group>
          <group
            name="Cylinder"
            position={[5.773, -2.749, 1.017]}
            rotation={[0, -0.349, -1.215]}
            scale={0.131}
          >
            <mesh
              name="Cylinder_0"
              geometry={nodes.Cylinder_0.geometry}
              material={materials.cdp_metal}
              position={[4.672, -3.974, 0.851]}
              scale={5.672}
            />
          </group>
          <group
            name="Cylinder001"
            position={[5.965, -3.927, 1.485]}
            rotation={[0, -0.349, -1.215]}
            scale={0.131}
          >
            <group
              name="Cylinder005"
              position={[21.97, -12.672, -2.085]}
              rotation={[0.001, -0.001, -1.773]}
              scale={6.122}
            >
              <mesh
                name="Cylinder005_0"
                geometry={nodes.Cylinder005_0.geometry}
                material={materials.cdp_metal}
                morphTargetDictionary={
                  nodes.Cylinder005_0.morphTargetDictionary
                }
                morphTargetInfluences={
                  nodes.Cylinder005_0.morphTargetInfluences
                }
                position={[0, -1.88, 0.012]}
                scale={2.048}
              />
            </group>
            <mesh
              name="Cylinder001_0"
              geometry={nodes.Cylinder001_0.geometry}
              material={materials.cdp_body}
              position={[14.65, -11.731, -0.04]}
              scale={24.247}
            />
            <mesh
              name="Cylinder001_1"
              geometry={nodes.Cylinder001_1.geometry}
              material={materials.gloss}
              position={[14.652, -11.73, -0.04]}
              scale={24.261}
            />
            <mesh
              name="Cylinder001_2"
              geometry={nodes.Cylinder001_2.geometry}
              material={materials.white_light}
              position={[36.394, -24.236, 1.18]}
              scale={3.916}
            />
            <mesh
              name="Cylinder001_3"
              geometry={nodes.Cylinder001_3.geometry}
              material={materials.cdp_plastic}
              position={[14.498, -11.971, -0.002]}
              scale={24.077}
            />
          </group>
          <group
            name="Cylinder002"
            position={[5.773, -2.749, 1.017]}
            rotation={[0, -0.349, 0.094]}
            scale={0.131}
          >
            <mesh
              name="Cylinder002_0"
              geometry={nodes.Cylinder002_0.geometry}
              material={materials.cdp_metal}
              position={[-41.826, 4.97, 15.538]}
              scale={43.507}
            />
          </group>
          <group
            name="Cylinder003"
            position={[4.836, -0.934, 0.803]}
            rotation={[0, -Math.PI / 9, 0.053]}
            scale={0.801}
          >
            <mesh
              name="Cylinder003_0"
              geometry={nodes.Cylinder003_0.geometry}
              material={materials.cdp_metal}
              morphTargetDictionary={nodes.Cylinder003_0.morphTargetDictionary}
              morphTargetInfluences={nodes.Cylinder003_0.morphTargetInfluences}
              position={[-0.014, 0.114, 0.008]}
              scale={4.042}
            />
          </group>
          <group
            name="Cylinder006"
            position={[2.514, -10.75, 1.388]}
            rotation={[-1.8, 1.145, 1.513]}
            scale={0.175}
          >
            <mesh
              name="Cylinder006_0"
              geometry={nodes.Cylinder006_0.geometry}
              material={materials.cdp_body}
              position={[-0.053, -0.107, 8.619]}
              scale={9.265}
            />
            <mesh
              name="Cylinder006_1"
              geometry={nodes.Cylinder006_1.geometry}
              material={materials.gloss}
              position={[-0.054, 0.186, 8.62]}
              scale={9.285}
            />
            <mesh
              name="Cylinder006_2"
              geometry={nodes.Cylinder006_2.geometry}
              material={materials.cdp_plastic}
              position={[0.377, 0.322, 8.509]}
              scale={9.15}
            />
            <mesh
              name="Cylinder006_3"
              geometry={nodes.Cylinder006_3.geometry}
              material={materials.cdp_metal}
              position={[0.488, 0.534, 8.324]}
              scale={6.683}
            />
            <mesh
              name="Cylinder006_4"
              geometry={nodes.Cylinder006_4.geometry}
              material={materials.white_light}
              position={[0.717, 0.102, 8.104]}
              scale={5.416}
            />
          </group>
          <group
            name="Cylinder007"
            position={[2.413, -10.795, 1.399]}
            rotation={[1.342, -1.145, -1.811]}
            scale={0.175}
          >
            <mesh
              name="Cylinder007_0"
              geometry={nodes.Cylinder007_0.geometry}
              material={materials.cdp_plastic}
              position={[0.677, -7.194, 12.872]}
              scale={13.411}
            />
          </group>
          <group
            name="Cylinder009"
            position={[0, -10.001, 1.024]}
            rotation={[-0.698, 0, 0]}
          >
            <group
              name="Cylinder010"
              position={[0, 1.435, -0.547]}
              rotation={[0, Math.PI / 2, 0]}
            >
              <group
                name="Torus001"
                position={[0, 2.42, 0]}
                rotation={[0, -Math.PI / 2, 0]}
                scale={[1.266, 1, 1]}
              >
                <group name="tyre" position={[0.011, 0, 0]}>
                  <mesh
                    name="Torus001_0"
                    geometry={nodes.Torus001_0.geometry}
                    material={materials.cdp_plastic}
                    position={[-0.011, 0, 0]}
                    scale={1.328}
                  />
                  <mesh
                    name="Torus001_0_1"
                    geometry={nodes.Torus001_0_1.geometry}
                    material={materials.cdp_metal}
                    position={[-0.011, 0, 0]}
                    scale={0.895}
                  />
                </group>
              </group>
              <mesh
                name="Cylinder010_0"
                geometry={nodes.Cylinder010_0.geometry}
                material={materials.cdp_metal}
                position={[0, 1.751, -0.42]}
                scale={1.385}
              />
            </group>
            <mesh
              name="Cylinder009_0"
              geometry={nodes.Cylinder009_0.geometry}
              material={materials.cdp_plastic}
              position={[-0.002, 0, 0]}
              scale={0.473}
            />
          </group>
          <group
            name="Cylinder011"
            position={[0, -7.4, 1.587]}
            rotation={[2.197, 0, 0]}
            scale={0.644}
          >
            <mesh
              name="Cylinder011_0"
              geometry={nodes.Cylinder011_0.geometry}
              material={materials.cdp_metal}
              morphTargetDictionary={nodes.Cylinder011_0.morphTargetDictionary}
              morphTargetInfluences={nodes.Cylinder011_0.morphTargetInfluences}
              position={[-0.034, -0.049, -0.214]}
              scale={4.437}
            />
          </group>
          <group
            name="Cylinder012"
            position={[5.289, 4.289, 1.612]}
            rotation={[-0.873, 0, 0]}
          >
            <group
              name="Cylinder004"
              position={[0, 1.635, -0.547]}
              rotation={[0, 1.57, 0]}
            >
              <group
                name="Torus000"
                position={[0.001, 2.419, -0.027]}
                rotation={[-1.584, -1.549, -1.584]}
                scale={[1.266, 1, 1]}
              >
                <mesh
                  name="Torus000_0"
                  geometry={nodes.Torus000_0.geometry}
                  material={materials.cdp_plastic}
                  scale={1.328}
                />
                <mesh
                  name="Torus000_0_1"
                  geometry={nodes.Torus000_0_1.geometry}
                  material={materials.cdp_metal}
                  scale={0.896}
                />
              </group>
              <mesh
                name="Cylinder004_0"
                geometry={nodes.Cylinder004_0.geometry}
                material={materials.cdp_metal}
                position={[0, 1.752, -0.42]}
                scale={1.385}
              />
              <mesh
                name="Cylinder004_1"
                geometry={nodes.Cylinder004_1.geometry}
                material={materials.white_light}
                position={[0, 2.42, -0.94]}
                scale={0.326}
              />
            </group>
            <mesh
              name="Cylinder012_0"
              geometry={nodes.Cylinder012_0.geometry}
              material={materials.cdp_metal}
              position={[0, 0.92, -0.372]}
              scale={1.077}
            />
          </group>
          <group
            name="Cylinder013"
            position={[-3.821, 14.727, 4.705]}
            rotation={[3.137, 0.421, 0.228]}
          >
            <mesh
              name="Cylinder013_0"
              geometry={nodes.Cylinder013_0.geometry}
              material={materials.cdp_metal}
              position={[-0.01, 0, 0.432]}
              scale={0.61}
            />
            <mesh
              name="Cylinder013_1"
              geometry={nodes.Cylinder013_1.geometry}
              material={materials.cdp_body}
              position={[-0.406, -0.694, 1.311]}
              scale={2.238}
            />
            <mesh
              name="Cylinder013_2"
              geometry={nodes.Cylinder013_2.geometry}
              material={materials.gloss}
              position={[-0.406, -0.694, 1.311]}
              scale={2.247}
            />
          </group>
          <group
            name="Cylinder014"
            position={[-4.761, 11.355, 3.661]}
            rotation={[-2.984, 0.086, 0.181]}
          >
            <mesh
              name="Cylinder014_0"
              geometry={nodes.Cylinder014_0.geometry}
              material={materials.cdp_metal}
              position={[-0.001, 0, 0.432]}
              scale={0.61}
            />
            <mesh
              name="Cylinder014_1"
              geometry={nodes.Cylinder014_1.geometry}
              material={materials.cdp_body}
              position={[-0.239, -0.857, 1.752]}
              scale={2.605}
            />
            <mesh
              name="Cylinder014_2"
              geometry={nodes.Cylinder014_2.geometry}
              material={materials.gloss}
              position={[-0.239, -0.856, 1.752]}
              scale={2.613}
            />
            <mesh
              name="Cylinder014_3"
              geometry={nodes.Cylinder014_3.geometry}
              material={materials.white_light}
              position={[-0.084, -3.543, 2.185]}
              scale={0.354}
            />
          </group>
          <group
            name="Cylinder017"
            position={[4.761, 11.355, 3.661]}
            rotation={[0.205, -0.172, 0.183]}
          >
            <group name="Cylinder015" rotation={[0, 0.262, 0]}>
              <mesh
                name="Cylinder015_0"
                geometry={nodes.Cylinder015_0.geometry}
                material={materials.cdp_metal}
                position={[0.001, 0, -0.432]}
                scale={0.61}
              />
              <mesh
                name="Cylinder015_1"
                geometry={nodes.Cylinder015_1.geometry}
                material={materials.cdp_body}
                position={[0.239, 0.857, -1.752]}
                scale={2.605}
              />
              <mesh
                name="Cylinder015_2"
                geometry={nodes.Cylinder015_2.geometry}
                material={materials.gloss}
                position={[0.239, 0.856, -1.752]}
                scale={2.613}
              />
              <mesh
                name="Cylinder015_3"
                geometry={nodes.Cylinder015_3.geometry}
                material={materials.white_light}
                position={[0.084, 3.543, -2.185]}
                scale={0.354}
              />
            </group>
            <mesh
              name="Cylinder017_0"
              geometry={nodes.Cylinder017_0.geometry}
              material={materials.cdp_metal}
              position={[-4.658, 0.873, 0.805]}
              scale={4.813}
            />
          </group>
          <group
            name="Cylinder018"
            position={[3.821, 14.727, 4.705]}
            rotation={[-0.237, 0.99, 0.386]}
          >
            <group name="Cylinder019" rotation={[0, -0.593, 0]}>
              <mesh
                name="Cylinder019_0"
                geometry={nodes.Cylinder019_0.geometry}
                material={materials.cdp_metal}
                position={[0.01, 0, -0.432]}
                scale={0.61}
              />
              <mesh
                name="Cylinder019_1"
                geometry={nodes.Cylinder019_1.geometry}
                material={materials.cdp_body}
                position={[0.406, 0.694, -1.311]}
                scale={2.238}
              />
              <mesh
                name="Cylinder019_2"
                geometry={nodes.Cylinder019_2.geometry}
                material={materials.gloss}
                position={[0.406, 0.694, -1.311]}
                scale={2.247}
              />
            </group>
            <mesh
              name="Cylinder018_0"
              geometry={nodes.Cylinder018_0.geometry}
              material={materials.cdp_metal}
              position={[-2.198, 0.809, -3.177]}
              scale={3.456}
            />
          </group>
          <group
            name="Cylinder020"
            position={[0, -10.001, 1.024]}
            rotation={[-0.698, 0, 0]}
          >
            <mesh
              name="Cylinder020_0"
              geometry={nodes.Cylinder020_0.geometry}
              material={materials.cdp_metal}
              position={[0, 0.82, -0.372]}
              scale={0.977}
            />
          </group>
          <group
            name="Cylinder021"
            position={[-5.289, 4.289, 1.612]}
            rotation={[-0.873, 0, 0]}
          >
            <group
              name="Cylinder022"
              position={[0.001, 1.641, -0.53]}
              rotation={[Math.PI / 2, 0, 0]}
            >
              <group
                name="Torus002"
                position={[0.008, -0.001, -2.419]}
                rotation={[1.549, 0, -0.008]}
              >
                <mesh
                  name="Torus002_1"
                  geometry={nodes.Torus002_1.geometry}
                  material={materials.cdp_metal}
                  scale={0.896}
                />
                <mesh
                  name="Torus002_1_1"
                  geometry={nodes.Torus002_1_1.geometry}
                  material={materials.cdp_plastic}
                  scale={1.328}
                />
              </group>
              <mesh
                name="Cylinder022_0"
                geometry={nodes.Cylinder022_0.geometry}
                material={materials.cdp_metal}
                position={[0.414, 0, -1.751]}
                scale={1.388}
              />
              <mesh
                name="Cylinder022_1"
                geometry={nodes.Cylinder022_1.geometry}
                material={materials.white_light}
                position={[0.92, 0, -2.427]}
                scale={0.326}
              />
            </group>
            <mesh
              name="Cylinder021_0"
              geometry={nodes.Cylinder021_0.geometry}
              material={materials.cdp_metal}
              position={[0, 0.92, -0.372]}
              scale={1.077}
            />
          </group>
          <group
            name="Cylinder023"
            position={[5.965, -3.927, 1.485]}
            rotation={[0, -0.349, -1.215]}
            scale={0.131}
          >
            <mesh
              name="Cylinder023_0"
              geometry={nodes.Cylinder023_0.geometry}
              material={materials.cdp_metal}
              position={[12.582, -6.114, 1.385]}
              scale={13.917}
            />
          </group>
          <group
            name="Cylinder024"
            position={[-2.514, -10.75, 1.388]}
            rotation={[1.342, 1.145, 1.513]}
          >
            <mesh
              name="Cylinder024_0"
              geometry={nodes.Cylinder024_0.geometry}
              material={materials.cdp_body}
              position={[0.009, 0.019, -1.51]}
              scale={1.623}
            />
            <mesh
              name="Cylinder024_1"
              geometry={nodes.Cylinder024_1.geometry}
              material={materials.gloss}
              position={[0.009, -0.033, -1.51]}
              scale={1.627}
            />
            <mesh
              name="Cylinder024_2"
              geometry={nodes.Cylinder024_2.geometry}
              material={materials.cdp_plastic}
              position={[-0.066, -0.056, -1.491]}
              scale={1.603}
            />
            <mesh
              name="Cylinder024_3"
              geometry={nodes.Cylinder024_3.geometry}
              material={materials.cdp_metal}
              position={[-0.086, -0.094, -1.458]}
              scale={1.171}
            />
            <mesh
              name="Cylinder024_4"
              geometry={nodes.Cylinder024_4.geometry}
              material={materials.white_light}
              position={[-0.126, -0.018, -1.42]}
              scale={0.949}
            />
          </group>
          <group
            name="Cylinder025"
            position={[-4.836, -0.934, 0.803]}
            rotation={[Math.PI, -Math.PI / 9, 0.053]}
          >
            <mesh
              name="Cylinder025_0"
              geometry={nodes.Cylinder025_0.geometry}
              material={materials.cdp_metal}
              morphTargetDictionary={nodes.Cylinder025_0.morphTargetDictionary}
              morphTargetInfluences={nodes.Cylinder025_0.morphTargetInfluences}
              position={[0.011, -0.092, -0.006]}
              scale={3.239}
            />
          </group>
          <group
            name="Cylinder026"
            position={[-5.965, -3.927, 1.485]}
            rotation={[3.142, -0.349, -1.215]}
          >
            <group
              name="Cylinder027"
              position={[-2.875, 1.659, 0.273]}
              rotation={[0.001, -0.001, -1.773]}
            >
              <mesh
                name="Cylinder027_0"
                geometry={nodes.Cylinder027_0.geometry}
                material={materials.cdp_metal}
                morphTargetDictionary={
                  nodes.Cylinder027_0.morphTargetDictionary
                }
                morphTargetInfluences={
                  nodes.Cylinder027_0.morphTargetInfluences
                }
                position={[0, 1.506, -0.01]}
                scale={1.641}
              />
            </group>
            <mesh
              name="Cylinder026_0"
              geometry={nodes.Cylinder026_0.geometry}
              material={materials.cdp_body}
              position={[-1.917, 1.535, 0.005]}
              scale={3.174}
            />
            <mesh
              name="Cylinder026_1"
              geometry={nodes.Cylinder026_1.geometry}
              material={materials.gloss}
              position={[-1.918, 1.535, 0.005]}
              scale={3.175}
            />
            <mesh
              name="Cylinder026_2"
              geometry={nodes.Cylinder026_2.geometry}
              material={materials.white_light}
              position={[-4.763, 3.172, -0.154]}
              scale={0.513}
            />
            <mesh
              name="Cylinder026_3"
              geometry={nodes.Cylinder026_3.geometry}
              material={materials.cdp_plastic}
              position={[-1.898, 1.567, 0]}
              scale={3.151}
            />
            <mesh
              name="Cylinder026_4"
              geometry={nodes.Cylinder026_4.geometry}
              material={materials.cdp_metal}
              position={[-1.647, 0.8, -0.181]}
              scale={1.821}
            />
          </group>
          <group
            name="Cylinder028"
            position={[-5.773, -2.749, 1.017]}
            rotation={[3.142, -0.349, -1.215]}
          >
            <mesh
              name="Cylinder028_0"
              geometry={nodes.Cylinder028_0.geometry}
              material={materials.cdp_metal}
              position={[-0.611, 0.52, -0.111]}
              scale={0.742}
            />
          </group>
          <group name="Plane001" position={[4.637, -8.238, 0]}>
            <mesh
              name="Plane001_0"
              geometry={nodes.Plane001_0.geometry}
              material={materials.cdp_metal}
              position={[-4.637, 1.258, 1.672]}
              scale={4.475}
            />
          </group>
          <group
            name="Plane002"
            position={[-2.634, -10.819, 1.921]}
            rotation={[-Math.PI, 0, 0]}
          >
            <mesh
              name="Plane002_0"
              geometry={nodes.Plane002_0.geometry}
              material={materials.cdp_body}
              position={[-1.299, -3.117, -0.307]}
              scale={3.192}
            />
            <mesh
              name="Plane002_1"
              geometry={nodes.Plane002_1.geometry}
              material={materials.gloss}
              position={[-1.299, -3.117, -0.308]}
              scale={3.195}
            />
            <mesh
              name="Plane002_2"
              geometry={nodes.Plane002_2.geometry}
              material={materials.cdp_metal}
              position={[-0.638, -2.123, -0.398]}
              scale={0.9}
            />
            <mesh
              name="Plane002_3"
              geometry={nodes.Plane002_3.geometry}
              material={materials.cdp_plastic}
              position={[-1.282, -3.13, -0.272]}
              scale={3.178}
            />
          </group>
          <group name="Plane003" position={[4.637, -8.238, -0.153]}>
            <mesh
              name="Plane003_0"
              geometry={nodes.Plane003_0.geometry}
              material={materials.cdp_metal}
              position={[-4.637, -0.36, 1.531]}
              scale={1.593}
            />
          </group>
          <group
            name="Plane004"
            position={[2.634, -10.819, 1.921]}
            scale={[0.913, 1.028, 1.07]}
          >
            <mesh
              name="Plane004_0"
              geometry={nodes.Plane004_0.geometry}
              material={materials.cdp_body}
              position={[1.422, 3.03, 0.287]}
              scale={3.104}
            />
            <mesh
              name="Plane004_1"
              geometry={nodes.Plane004_1.geometry}
              material={materials.gloss}
              position={[1.422, 3.031, 0.288]}
              scale={3.107}
            />
            <mesh
              name="Plane004_2"
              geometry={nodes.Plane004_2.geometry}
              material={materials.cdp_metal}
              position={[0.698, 2.064, 0.372]}
              scale={0.986}
            />
            <mesh
              name="Plane004_3"
              geometry={nodes.Plane004_3.geometry}
              material={materials.cdp_plastic}
              position={[1.404, 3.044, 0.254]}
              scale={3.09}
            />
          </group>
          <group name="Plane006" position={[4.637, -8.238, 0]}>
            <mesh
              name="Plane006_0"
              geometry={nodes.Plane006_0.geometry}
              material={materials.cdp_metal}
              position={[-4.637, 1.637, 1.094]}
              scale={5.084}
            />
          </group>
          <group
            name="Plane013"
            position={[0.709, 8.7, 5.385]}
            scale={[0.561, 1.011, 0.561]}
          >
            <mesh
              name="Plane013_0"
              geometry={nodes.Plane013_0.geometry}
              material={materials.thruster}
              position={[0, 2.142, 0]}
              scale={2.32}
            />
          </group>
          <group name="Plane014" position={[0.11, 8.076, 4.462]}>
            <mesh
              name="Plane014_0"
              geometry={nodes.Plane014_0.geometry}
              material={materials.thruster}
              position={[0, 2.142, 0]}
              scale={2.32}
            />
          </group>
          <group
            name="Plane015"
            position={[1.494, 8.824, 4.785]}
            scale={[0.561, 1.011, 0.561]}
          >
            <mesh
              name="Plane015_0"
              geometry={nodes.Plane015_0.geometry}
              material={materials.thruster}
              position={[0, 2.142, 0]}
              scale={2.32}
            />
          </group>
          <group
            name="Plane016"
            position={[-1.321, 6.89, 4.462]}
            scale={[0.561, 1.011, 0.561]}
          >
            <mesh
              name="Plane016_0"
              geometry={nodes.Plane016_0.geometry}
              material={materials.thruster}
              position={[0, 2.142, 0]}
              scale={2.32}
            />
          </group>
          <group
            name="Plane017"
            position={[-0.951, 10.143, 4.462]}
            scale={[0.561, 1.011, 0.561]}
          >
            <mesh
              name="Plane017_0"
              geometry={nodes.Plane017_0.geometry}
              material={materials.thruster}
              position={[0, 2.142, 0]}
              scale={2.32}
            />
          </group>
          <group
            name="Plane018"
            position={[-0.582, 6.869, 4.462]}
            scale={[0.561, 1.011, 0.561]}
          >
            <mesh
              name="Plane018_0"
              geometry={nodes.Plane018_0.geometry}
              material={materials.thruster}
              position={[0, 2.142, 0]}
              scale={2.32}
            />
          </group>
          <mesh
            name="car_0"
            geometry={nodes.car_0.geometry}
            material={materials.cdp_metal}
            position={[0, 13.586, 5.269]}
            scale={4.185}
          />
          <mesh
            name="car001_0"
            geometry={nodes.car001_0.geometry}
            material={materials.cdp_body}
            position={[0, -7.794, 3.033]}
            scale={4.491}
          />
          <mesh
            name="car001_1"
            geometry={nodes.car001_1.geometry}
            material={materials.gloss}
            position={[0, -7.797, 3.033]}
            scale={4.497}
          />
          <mesh
            name="car002_0"
            geometry={nodes.car002_0.geometry}
            material={materials.cdp_body}
            position={[0, -1.407, 4.933]}
            scale={3.074}
          />
          <mesh
            name="car003_0"
            geometry={nodes.car003_0.geometry}
            material={materials.cdp_metal}
            position={[0, 1.868, -0.577]}
            scale={1.96}
          />
          <mesh
            name="car004_0"
            geometry={nodes.car004_0.geometry}
            material={materials.white_light}
            position={[0, 0.3, 6.168]}
            scale={0.422}
          />
          <mesh
            name="car005_0"
            geometry={nodes.car005_0.geometry}
            material={materials.cdp_plastic}
            position={[1.082, 9.331, 6.231]}
            scale={2.877}
          />
          <mesh
            name="car005_1"
            geometry={nodes.car005_1.geometry}
            material={materials.cdp_metal}
            position={[1.082, 9.393, 6.382]}
            scale={2.941}
          />
          <mesh
            name="car006_0"
            geometry={nodes.car006_0.geometry}
            material={materials.cdp_plastic}
            position={[0, 2.614, 2.753]}
            scale={14.838}
          />
          <mesh
            name="car008_0"
            geometry={nodes.car008_0.geometry}
            material={materials.thruster}
            morphTargetDictionary={nodes.car008_0.morphTargetDictionary}
            morphTargetInfluences={nodes.car008_0.morphTargetInfluences}
            position={[0.648, 6.958, 4.101]}
            scale={6.969}
          />
          <mesh
            name="car009_0"
            geometry={nodes.car009_0.geometry}
            material={materials.cdp_metal}
            position={[0, -9.022, 1.836]}
            scale={1.291}
          />
          <mesh
            name="car011_0"
            geometry={nodes.car011_0.geometry}
            material={materials.cdp_plastic}
            position={[0, -0.336, -0.746]}
            scale={1.836}
          />
          <mesh
            name="car013_0"
            geometry={nodes.car013_0.geometry}
            material={materials.cdp_metal}
            position={[0, 14.949, 6.021]}
            scale={1.756}
          />
          <mesh
            name="car015_0"
            geometry={nodes.car015_0.geometry}
            material={materials.cdp_metal}
            position={[0, 4.33, 1.586]}
            scale={5.163}
          />
          <mesh
            name="car016_0"
            geometry={nodes.car016_0.geometry}
            material={materials.cdp_metal}
            position={[0, 5.358, 1.563]}
            scale={9.653}
          />
          <mesh
            name="car017_0"
            geometry={nodes.car017_0.geometry}
            material={materials.white_light}
            position={[0, 14.859, 2.518]}
            scale={0.313}
          />
          <mesh
            name="car019_0"
            geometry={nodes.car019_0.geometry}
            material={materials.cdp_body}
            position={[0, 2.976, 3.817]}
            scale={14.775}
          />
          <mesh
            name="car019_1"
            geometry={nodes.car019_1.geometry}
            material={materials.gloss}
            position={[0, 3.094, 3.117]}
            scale={14.665}
          />
          <mesh
            name="Cube000_0"
            geometry={nodes.Cube000_0.geometry}
            material={materials.cdp_metal}
            position={[0, -4.489, 0.313]}
            scale={5.163}
          />
          <mesh
            name="Cube002_0"
            geometry={nodes.Cube002_0.geometry}
            material={materials.cdp_plastic}
            position={[0, -7.46, 0.248]}
            scale={5.672}
          />
          <mesh
            name="Cube003_0"
            geometry={nodes.Cube003_0.geometry}
            material={materials.cdp_plastic}
            position={[0, 0.562, -0.914]}
            scale={5.257}
          />
          <mesh
            name="Cube004_0"
            geometry={nodes.Cube004_0.geometry}
            material={materials.cdp_plastic}
            position={[0, -6.884, 1.101]}
            scale={1.338}
          />
          <mesh
            name="Cube008_0"
            geometry={nodes.Cube008_0.geometry}
            material={materials.cdp_metal}
            position={[0, -7.06, 0.164]}
            scale={5.672}
          />
          <mesh
            name="Cube009_0"
            geometry={nodes.Cube009_0.geometry}
            material={materials.cdp_metal}
            position={[0, -9.329, 0.437]}
            scale={3.331}
          />
          <mesh
            name="Cube013_0"
            geometry={nodes.Cube013_0.geometry}
            material={materials.cdp_metal}
            position={[0, -7.064, -0.056]}
            scale={5.119}
          />
          <mesh
            name="Cylinder016_0"
            geometry={nodes.Cylinder016_0.geometry}
            material={materials.cdp_metal}
            position={[0, 12.042, 2.623]}
            scale={3.998}
          />
          <mesh
            name="Plane_0"
            geometry={nodes.Plane_0.geometry}
            material={materials.cdp_metal}
            position={[0, -8.806, 0.486]}
            scale={2.476}
          />
          <mesh
            name="Plane007_0"
            geometry={nodes.Plane007_0.geometry}
            material={materials.thruster}
            position={[8.057, -19.92, 1.196]}
            scale={0}
          />
          <mesh
            name="Plane008_0"
            geometry={nodes.Plane008_0.geometry}
            material={materials.thruster}
            position={[-9.164, -15.834, 1.196]}
            scale={0}
          />
          <mesh
            name="Plane009_0"
            geometry={nodes.Plane009_0.geometry}
            material={materials.thruster}
            position={[-2.505, -25.327, -1.805]}
            scale={0}
          />
          <mesh
            name="Plane010_0"
            geometry={nodes.Plane010_0.geometry}
            material={materials.thruster}
            position={[4.268, -20.196, 1.196]}
            scale={0}
          />
          <mesh
            name="Plane011_0"
            geometry={nodes.Plane011_0.geometry}
            material={materials.thruster}
            position={[-4.457, -30.773, 6.362]}
            scale={0}
          />
          <mesh
            name="Plane012_0"
            geometry={nodes.Plane012_0.geometry}
            material={materials.thruster}
            position={[-2.505, -5.961, 10.229]}
            scale={0}
          />
          <mesh
            name="Plane019_0"
            geometry={nodes.Plane019_0.geometry}
            material={materials.thruster}
            position={[-0.582, -24.914, 7.175]}
            scale={0}
          />
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/models/cybercar-compressed.glb");
