/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ./public/models/maclarn.glb --keepnames -o ./src/components/maclarn/index.tsx 
*/

import * as THREE from "three";
import { useRef, type JSX } from "react";
import { useGLTF } from "@react-three/drei";
import { type GLTF } from "three-stdlib";
import { useFrame } from "@react-three/fiber";

type GLTFResult = GLTF & {
  nodes: {
    body: THREE.Mesh;
    Object_10: THREE.Mesh;
    Object_11: THREE.Mesh;
    Object_12: THREE.Mesh;
    Object_13: THREE.Mesh;
    Object_14: THREE.Mesh;
    Object_15: THREE.Mesh;
    Object_16: THREE.Mesh;
    Object_17: THREE.Mesh;
    Object_18: THREE.Mesh;
    Object_19: THREE.Mesh;
    Object_20: THREE.Mesh;
    Object_21: THREE.Mesh;
    Object_22: THREE.Mesh;
    Object_23: THREE.Mesh;
    Object_24: THREE.Mesh;
    Object_25: THREE.Mesh;
    Object_26: THREE.Mesh;
    Object_27: THREE.Mesh;
    Object_28: THREE.Mesh;
    Object_29: THREE.Mesh;
    Object_30: THREE.Mesh;
    Object_31: THREE.Mesh;
    Object_32: THREE.Mesh;
    Object_33: THREE.Mesh;
    Object_34: THREE.Mesh;
    Object_35: THREE.Mesh;
    Object_36: THREE.Mesh;
    Object_37: THREE.Mesh;
    Object_38: THREE.Mesh;
    Object_39: THREE.Mesh;
    Object_40: THREE.Mesh;
    Object_41: THREE.Mesh;
    Object_42: THREE.Mesh;
    Object_43: THREE.Mesh;
    Object_44: THREE.Mesh;
    Object_45: THREE.Mesh;
    Object_46: THREE.Mesh;
    Object_47: THREE.Mesh;
    Object_48: THREE.Mesh;
    Object_49: THREE.Mesh;
    Object_50: THREE.Mesh;
    Object_51: THREE.Mesh;
    Object_7: THREE.Mesh;
    Object_8: THREE.Mesh;
    Object_9: THREE.Mesh;
    Object_78: THREE.Mesh;
    Object_79: THREE.Mesh;
    Object_80: THREE.Mesh;
    Object_81: THREE.Mesh;
    Object_83: THREE.Mesh;
    Object_84: THREE.Mesh;
    Object_89: THREE.Mesh;
    Object_90: THREE.Mesh;
    Object_91: THREE.Mesh;
    Object_92: THREE.Mesh;
    Object_94: THREE.Mesh;
    Object_95: THREE.Mesh;
    Object_56: THREE.Mesh;
    Object_57: THREE.Mesh;
    Object_58: THREE.Mesh;
    Object_59: THREE.Mesh;
    Object_61: THREE.Mesh;
    Object_62: THREE.Mesh;
    Object_47001: THREE.Mesh;
    Object_47001_1: THREE.Mesh;
    Object_47001_2: THREE.Mesh;
    Object_47003: THREE.Mesh;
    Object_47003_1: THREE.Mesh;
    Object_47003_2: THREE.Mesh;
    Object_47004: THREE.Mesh;
    Object_47004_1: THREE.Mesh;
    Object_47004_2: THREE.Mesh;
    Object_47005: THREE.Mesh;
    Object_47005_1: THREE.Mesh;
    Object_47005_2: THREE.Mesh;
    Object_67: THREE.Mesh;
    Object_68: THREE.Mesh;
    Object_69: THREE.Mesh;
    Object_70: THREE.Mesh;
    Object_72: THREE.Mesh;
    Object_73: THREE.Mesh;
    Object_112: THREE.Mesh;
    Object_113: THREE.Mesh;
    Object_114: THREE.Mesh;
    Object_115: THREE.Mesh;
    Object_116: THREE.Mesh;
    Object_117: THREE.Mesh;
    Object_120: THREE.Mesh;
    Object_121: THREE.Mesh;
    Object_122: THREE.Mesh;
    Object_123: THREE.Mesh;
    Object_124: THREE.Mesh;
    Object_125: THREE.Mesh;
    Object_100: THREE.Mesh;
    Object_101: THREE.Mesh;
    Object_102: THREE.Mesh;
    Object_98: THREE.Mesh;
    Object_99: THREE.Mesh;
    Object_105: THREE.Mesh;
    Object_106: THREE.Mesh;
    Object_107: THREE.Mesh;
    Object_108: THREE.Mesh;
    Object_109: THREE.Mesh;
  };
  materials: {
    ["Matte__FF999999_.001"]: THREE.MeshStandardMaterial;
    ["leather__spec_.001"]: THREE.MeshStandardMaterial;
    stitches: THREE.MeshStandardMaterial;
    ["mesh2__spec_.001"]: THREE.MeshStandardMaterial;
    spiegels: THREE.MeshPhysicalMaterial;
    Glass: THREE.MeshStandardMaterial;
    ["badges__spec_.001"]: THREE.MeshStandardMaterial;
    ["carbonint__spec_.001"]: THREE.MeshStandardMaterial;
    ["misc__spec_.001"]: THREE.MeshStandardMaterial;
    ["vehiclelights128.001"]: THREE.MeshStandardMaterial;
    ["vehiclelights1.001"]: THREE.MeshStandardMaterial;
    ["vehiclelights2.001"]: THREE.MeshStandardMaterial;
    ["vehiclelights3.001"]: THREE.MeshStandardMaterial;
    binnen_koplamp: THREE.MeshStandardMaterial;
    ["steeringwheel__s.001"]: THREE.MeshStandardMaterial;
    ["water__spec_.001"]: THREE.MeshStandardMaterial;
    ["bumper_frame__sp.001"]: THREE.MeshStandardMaterial;
    ["Matte__FF00001.001"]: THREE.MeshStandardMaterial;
    ["Matte__FF00002.001"]: THREE.MeshStandardMaterial;
    ["Matte__BA000000_.001"]: THREE.MeshStandardMaterial;
    ["Material.003"]: THREE.MeshStandardMaterial;
    ["guages__spec_.001"]: THREE.MeshStandardMaterial;
    ["carpet__spec_.001"]: THREE.MeshStandardMaterial;
    ["mclarenint__spec.001"]: THREE.MeshStandardMaterial;
    ANgle_eye_inside: THREE.MeshStandardMaterial;
    angle_eyes: THREE.MeshStandardMaterial;
    Carbon: THREE.MeshStandardMaterial;
    ["Carbon.001"]: THREE.MeshStandardMaterial;
    ["Material.069"]: THREE.MeshStandardMaterial;
    ["Material.070"]: THREE.MeshStandardMaterial;
    ["Material.008"]: THREE.MeshStandardMaterial;
    ["Material.009"]: THREE.MeshStandardMaterial;
    ["Material.036"]: THREE.MeshStandardMaterial;
    ["Material.004"]: THREE.MeshStandardMaterial;
    ["Material.005"]: THREE.MeshStandardMaterial;
    ["Material.016"]: THREE.MeshStandardMaterial;
    ["Material.017"]: THREE.MeshStandardMaterial;
    Exhaust: THREE.MeshStandardMaterial;
    Exhaust_inside: THREE.MeshStandardMaterial;
    ["Material.010"]: THREE.MeshStandardMaterial;
    ["Material.074"]: THREE.MeshStandardMaterial;
    mclaren_logo: THREE.MeshStandardMaterial;
    ["Matte__FF000000_.001"]: THREE.MeshStandardMaterial;
    koplamp_binnen: THREE.MeshStandardMaterial;
    ["cockpit__spec_.001"]: THREE.MeshStandardMaterial;
    ["SCUDO_Yellow.005"]: THREE.MeshStandardMaterial;
    ["Red_METAL.005"]: THREE.MeshStandardMaterial;
    ["BRAKES_4K.005"]: THREE.MeshStandardMaterial;
    ["Black_Metal.005"]: THREE.MeshStandardMaterial;
    ["koplamp_binnen.008"]: THREE.MeshStandardMaterial;
    ["mclaren_logo.004"]: THREE.MeshStandardMaterial;
    ["SCUDO_Yellow.002"]: THREE.MeshStandardMaterial;
    ["Red_METAL.002"]: THREE.MeshStandardMaterial;
    ["BRAKES_4K.002"]: THREE.MeshStandardMaterial;
    ["Black_Metal.002"]: THREE.MeshStandardMaterial;
    ["koplamp_binnen.002"]: THREE.MeshStandardMaterial;
    ["mclaren_logo.001"]: THREE.MeshStandardMaterial;
    ["SCUDO_Yellow.004"]: THREE.MeshStandardMaterial;
    ["Red_METAL.004"]: THREE.MeshStandardMaterial;
    ["BRAKES_4K.004"]: THREE.MeshStandardMaterial;
    ["Black_Metal.004"]: THREE.MeshStandardMaterial;
    ["koplamp_binnen.006"]: THREE.MeshStandardMaterial;
    ["mclaren_logo.003"]: THREE.MeshStandardMaterial;
    ["Tires2.004"]: THREE.MeshStandardMaterial;
    ["Silver_METAL.004"]: THREE.MeshStandardMaterial;
    ["Black_METAL1.004"]: THREE.MeshStandardMaterial;
    ["SCUDO_Yellow.003"]: THREE.MeshStandardMaterial;
    ["Red_METAL.003"]: THREE.MeshStandardMaterial;
    ["BRAKES_4K.003"]: THREE.MeshStandardMaterial;
    ["Black_Metal.003"]: THREE.MeshStandardMaterial;
    ["koplamp_binnen.004"]: THREE.MeshStandardMaterial;
    ["mclaren_logo.002"]: THREE.MeshStandardMaterial;
    ["Brake_Pad.005"]: THREE.MeshStandardMaterial;
    ["Silver_METAL.005"]: THREE.MeshStandardMaterial;
    ["Brake_Disc_1.005"]: THREE.MeshStandardMaterial;
    ["Black_METAL.005"]: THREE.MeshStandardMaterial;
    ["Black_MATTE.005"]: THREE.MeshStandardMaterial;
    ["mini_brake.001"]: THREE.MeshStandardMaterial;
    ["Brake_Pad.002"]: THREE.MeshStandardMaterial;
    ["Silver_METAL.002"]: THREE.MeshStandardMaterial;
    ["Brake_Disc_1.002"]: THREE.MeshStandardMaterial;
    ["Black_METAL.002"]: THREE.MeshStandardMaterial;
    ["Black_MATTE.002"]: THREE.MeshStandardMaterial;
    mini_brake: THREE.MeshStandardMaterial;
    ["Brake_Disc_1.004"]: THREE.MeshStandardMaterial;
    ["Black_METAL.004"]: THREE.MeshStandardMaterial;
    ["Black_MATTE.004"]: THREE.MeshStandardMaterial;
    ["Brake_Pad.004"]: THREE.MeshStandardMaterial;
    ["Brake_Pad.003"]: THREE.MeshStandardMaterial;
    ["Silver_METAL.003"]: THREE.MeshStandardMaterial;
    ["Brake_Disc_1.003"]: THREE.MeshStandardMaterial;
    ["Black_METAL.003"]: THREE.MeshStandardMaterial;
    ["Black_MATTE.003"]: THREE.MeshStandardMaterial;
  };
};

const TYRE_ROTATE_SPEED = 5;

export function McLaren(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF(
    "/models/maclarn.glb",
  ) as unknown as GLTFResult;

  const tyresRef = useRef<(THREE.Group<THREE.Object3DEventMap> | null)[]>([]);

  useFrame((_, dt) => {
    tyresRef.current.forEach((Tyre) => {
      if (Tyre) {
        Tyre.rotation.x += TYRE_ROTATE_SPEED * dt;
      }
    });
  });
  return (
    <group {...props} dispose={null}>
      <group
        name="Sketchfab_model"
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.648}
      >
        <group name="GLTF_SceneRootNode" rotation={[Math.PI / 2, 0, 0]}>
          <group name="Car_Rig_72" position={[-0.07, -0.089, 2.557]}>
            <group
              name="DEF-Body_1"
              position={[0, 0.409, -2.749]}
              rotation={[-1.571, 0, 0]}
            >
              <group
                name="mycar-body_0"
                position={[0, -0.032, -0.408]}
                rotation={[Math.PI / 2, 0, 0]}
              >
                <mesh
                  name="body"
                  geometry={nodes.body.geometry}
                  material={nodes.body.material}
                />
                <mesh
                  name="Object_10"
                  geometry={nodes.Object_10.geometry}
                  material={materials["Matte__FF999999_.001"]}
                />
                <mesh
                  name="Object_11"
                  geometry={nodes.Object_11.geometry}
                  material={materials["leather__spec_.001"]}
                />
                <mesh
                  name="Object_12"
                  geometry={nodes.Object_12.geometry}
                  material={materials.stitches}
                />
                <mesh
                  name="Object_13"
                  geometry={nodes.Object_13.geometry}
                  material={materials["mesh2__spec_.001"]}
                />
                <mesh
                  name="Object_14"
                  geometry={nodes.Object_14.geometry}
                  material={materials.spiegels}
                />
                <mesh
                  name="Object_15"
                  geometry={nodes.Object_15.geometry}
                  material={materials.Glass}
                />
                <mesh
                  name="Object_16"
                  geometry={nodes.Object_16.geometry}
                  material={materials["badges__spec_.001"]}
                />
                <mesh
                  name="Object_17"
                  geometry={nodes.Object_17.geometry}
                  material={materials["carbonint__spec_.001"]}
                />
                <mesh
                  name="Object_18"
                  geometry={nodes.Object_18.geometry}
                  material={materials["misc__spec_.001"]}
                />
                <mesh
                  name="Object_19"
                  geometry={nodes.Object_19.geometry}
                  material={materials["vehiclelights128.001"]}
                />
                <mesh
                  name="Object_20"
                  geometry={nodes.Object_20.geometry}
                  material={materials["vehiclelights1.001"]}
                />
                <mesh
                  name="Object_21"
                  geometry={nodes.Object_21.geometry}
                  material={materials["vehiclelights2.001"]}
                />
                <mesh
                  name="Object_22"
                  geometry={nodes.Object_22.geometry}
                  material={materials["vehiclelights3.001"]}
                />
                <mesh
                  name="Object_23"
                  geometry={nodes.Object_23.geometry}
                  material={materials.binnen_koplamp}
                />
                <mesh
                  name="Object_24"
                  geometry={nodes.Object_24.geometry}
                  material={materials["steeringwheel__s.001"]}
                />
                <mesh
                  name="Object_25"
                  geometry={nodes.Object_25.geometry}
                  material={materials["water__spec_.001"]}
                />
                <mesh
                  name="Object_26"
                  geometry={nodes.Object_26.geometry}
                  material={materials["bumper_frame__sp.001"]}
                />
                <mesh
                  name="Object_27"
                  geometry={nodes.Object_27.geometry}
                  material={materials["Matte__FF00001.001"]}
                />
                <mesh
                  name="Object_28"
                  geometry={nodes.Object_28.geometry}
                  material={materials["Matte__FF00002.001"]}
                />
                <mesh
                  name="Object_29"
                  geometry={nodes.Object_29.geometry}
                  material={materials["Matte__BA000000_.001"]}
                />
                <mesh
                  name="Object_30"
                  geometry={nodes.Object_30.geometry}
                  material={materials["Material.003"]}
                />
                <mesh
                  name="Object_31"
                  geometry={nodes.Object_31.geometry}
                  material={materials["guages__spec_.001"]}
                />
                <mesh
                  name="Object_32"
                  geometry={nodes.Object_32.geometry}
                  material={materials["carpet__spec_.001"]}
                />
                <mesh
                  name="Object_33"
                  geometry={nodes.Object_33.geometry}
                  material={materials["mclarenint__spec.001"]}
                />
                <mesh
                  name="Object_34"
                  geometry={nodes.Object_34.geometry}
                  material={materials.ANgle_eye_inside}
                />
                <mesh
                  name="Object_35"
                  geometry={nodes.Object_35.geometry}
                  material={materials.angle_eyes}
                />
                <mesh
                  name="Object_36"
                  geometry={nodes.Object_36.geometry}
                  material={materials.Carbon}
                />
                <mesh
                  name="Object_37"
                  geometry={nodes.Object_37.geometry}
                  material={materials["Carbon.001"]}
                />
                <mesh
                  name="Object_38"
                  geometry={nodes.Object_38.geometry}
                  material={materials["Material.069"]}
                />
                <mesh
                  name="Object_39"
                  geometry={nodes.Object_39.geometry}
                  material={materials["Material.070"]}
                />
                <mesh
                  name="Object_40"
                  geometry={nodes.Object_40.geometry}
                  material={materials["Material.008"]}
                />
                <mesh
                  name="Object_41"
                  geometry={nodes.Object_41.geometry}
                  material={materials["Material.009"]}
                />
                <mesh
                  name="Object_42"
                  geometry={nodes.Object_42.geometry}
                  material={materials["Material.036"]}
                />
                <mesh
                  name="Object_43"
                  geometry={nodes.Object_43.geometry}
                  material={materials["Material.004"]}
                />
                <mesh
                  name="Object_44"
                  geometry={nodes.Object_44.geometry}
                  material={materials["Material.005"]}
                />
                <mesh
                  name="Object_45"
                  geometry={nodes.Object_45.geometry}
                  material={materials["Material.016"]}
                />
                <mesh
                  name="Object_46"
                  geometry={nodes.Object_46.geometry}
                  material={materials["Material.017"]}
                />
                <mesh
                  name="Object_47"
                  geometry={nodes.Object_47.geometry}
                  material={materials.Exhaust}
                />
                <mesh
                  name="Object_48"
                  geometry={nodes.Object_48.geometry}
                  material={materials.Exhaust_inside}
                />
                <mesh
                  name="Object_49"
                  geometry={nodes.Object_49.geometry}
                  material={materials["Material.010"]}
                />
                <mesh
                  name="Object_50"
                  geometry={nodes.Object_50.geometry}
                  material={materials["Material.074"]}
                />
                <mesh
                  name="Object_51"
                  geometry={nodes.Object_51.geometry}
                  material={materials.mclaren_logo}
                />
                <mesh
                  name="Object_7"
                  geometry={nodes.Object_7.geometry}
                  material={materials["Matte__FF000000_.001"]}
                />
                <mesh
                  name="Object_8"
                  geometry={nodes.Object_8.geometry}
                  material={materials.koplamp_binnen}
                />
                <mesh
                  name="Object_9"
                  geometry={nodes.Object_9.geometry}
                  material={materials["cockpit__spec_.001"]}
                />
              </group>
            </group>
            <group
              name="DEF-WheelBkL_7"
              position={[1.403, 0.526, -4.885]}
              rotation={[-1.571, 0, 0]}
            >
              <group
                name="mycar-wheelBkL_6"
                position={[-1.403, -2.168, -0.526]}
                rotation={[Math.PI / 2, 0, 0]}
              >
                <mesh
                  name="Object_78"
                  geometry={nodes.Object_78.geometry}
                  material={materials["SCUDO_Yellow.005"]}
                  position={[1.495, 0.525, -2.168]}
                />
                <mesh
                  name="Object_79"
                  geometry={nodes.Object_79.geometry}
                  material={materials["Red_METAL.005"]}
                />
                <mesh
                  name="Object_80"
                  geometry={nodes.Object_80.geometry}
                  material={materials["BRAKES_4K.005"]}
                />
                <mesh
                  name="Object_81"
                  geometry={nodes.Object_81.geometry}
                  material={materials["Black_Metal.005"]}
                />
                <mesh
                  name="Object_83"
                  geometry={nodes.Object_83.geometry}
                  material={materials["koplamp_binnen.008"]}
                />
                <mesh
                  name="Object_84"
                  geometry={nodes.Object_84.geometry}
                  material={materials["mclaren_logo.004"]}
                />
              </group>
            </group>
            <group
              name="DEF-WheelBkR_9"
              position={[-1.38, 0.526, -4.889]}
              rotation={[-1.571, 0, 0]}
            >
              <group
                name="mycar-wheelBkR_8"
                position={[1.38, -2.173, -0.526]}
                rotation={[Math.PI / 2, 0, 0]}
              >
                <mesh
                  name="Object_89"
                  geometry={nodes.Object_89.geometry}
                  material={materials["SCUDO_Yellow.002"]}
                  position={[-1.472, 0.525, -2.173]}
                />
                <mesh
                  name="Object_90"
                  geometry={nodes.Object_90.geometry}
                  material={materials["Red_METAL.002"]}
                />
                <mesh
                  name="Object_91"
                  geometry={nodes.Object_91.geometry}
                  material={materials["BRAKES_4K.002"]}
                />
                <mesh
                  name="Object_92"
                  geometry={nodes.Object_92.geometry}
                  material={materials["Black_Metal.002"]}
                />
                <mesh
                  name="Object_94"
                  geometry={nodes.Object_94.geometry}
                  material={materials["koplamp_binnen.002"]}
                />
                <mesh
                  name="Object_95"
                  geometry={nodes.Object_95.geometry}
                  material={materials["mclaren_logo.001"]}
                />
              </group>
            </group>
            <group
              name="DEF-WheelFtL_3"
              position={[1.378, 0.527, -0.612]}
              rotation={[-1.571, 0, 0]}
            >
              <group
                name="mycar-wheelFtL_2"
                position={[-1.378, 2.104, -0.526]}
                rotation={[Math.PI / 2, 0, 0]}
              >
                <mesh
                  name="Object_56"
                  geometry={nodes.Object_56.geometry}
                  material={materials["SCUDO_Yellow.004"]}
                  position={[1.471, 0.525, 2.105]}
                />
                <mesh
                  name="Object_57"
                  geometry={nodes.Object_57.geometry}
                  material={materials["Red_METAL.004"]}
                />
                <mesh
                  name="Object_58"
                  geometry={nodes.Object_58.geometry}
                  material={materials["BRAKES_4K.004"]}
                  position={[1.346, 0.523, 2.105]}
                />
                <mesh
                  name="Object_59"
                  geometry={nodes.Object_59.geometry}
                  material={materials["Black_Metal.004"]}
                />
                <mesh
                  name="Object_61"
                  geometry={nodes.Object_61.geometry}
                  material={materials["koplamp_binnen.006"]}
                />
                <mesh
                  name="Object_62"
                  geometry={nodes.Object_62.geometry}
                  material={materials["mclaren_logo.003"]}
                />
                <group
                  name="tyre"
                  ref={(el) => (tyresRef.current[0] = el)}
                  position={[1.495, 0.525, -2.168]}
                >
                  <mesh
                    name="Object_47001"
                    geometry={nodes.Object_47001.geometry}
                    material={materials["Tires2.004"]}
                  />
                  <mesh
                    name="Object_47001_1"
                    geometry={nodes.Object_47001_1.geometry}
                    material={materials["Silver_METAL.004"]}
                  />
                  <mesh
                    name="Object_47001_2"
                    geometry={nodes.Object_47001_2.geometry}
                    material={materials["Black_METAL1.004"]}
                  />
                </group>
                <group
                  name="tyre001"
                  ref={(el) => (tyresRef.current[1] = el)}
                  position={[-1.472, 0.525, -2.173]}
                  rotation={[0, 0, Math.PI]}
                >
                  <mesh
                    name="Object_47003"
                    geometry={nodes.Object_47003.geometry}
                    material={materials["Tires2.004"]}
                  />
                  <mesh
                    name="Object_47003_1"
                    geometry={nodes.Object_47003_1.geometry}
                    material={materials["Silver_METAL.004"]}
                  />
                  <mesh
                    name="Object_47003_2"
                    geometry={nodes.Object_47003_2.geometry}
                    material={materials["Black_METAL1.004"]}
                  />
                </group>
                <group
                  name="tyre002"
                  ref={(el) => (tyresRef.current[2] = el)}
                  position={[-1.493, 0.525, 2.095]}
                  rotation={[0, 0, Math.PI]}
                >
                  <mesh
                    name="Object_47004"
                    geometry={nodes.Object_47004.geometry}
                    material={materials["Tires2.004"]}
                  />
                  <mesh
                    name="Object_47004_1"
                    geometry={nodes.Object_47004_1.geometry}
                    material={materials["Silver_METAL.004"]}
                  />
                  <mesh
                    name="Object_47004_2"
                    geometry={nodes.Object_47004_2.geometry}
                    material={materials["Black_METAL1.004"]}
                  />
                </group>
                <group
                  name="tyre003"
                  ref={(el) => (tyresRef.current[3] = el)}
                  position={[1.471, 0.525, 2.105]}
                >
                  <mesh
                    name="Object_47005"
                    geometry={nodes.Object_47005.geometry}
                    material={materials["Tires2.004"]}
                  />
                  <mesh
                    name="Object_47005_1"
                    geometry={nodes.Object_47005_1.geometry}
                    material={materials["Silver_METAL.004"]}
                  />
                  <mesh
                    name="Object_47005_2"
                    geometry={nodes.Object_47005_2.geometry}
                    material={materials["Black_METAL1.004"]}
                  />
                </group>
              </group>
            </group>
            <group
              name="DEF-WheelFtR_5"
              position={[-1.401, 0.527, -0.621]}
              rotation={[-1.571, 0, 0]}
            >
              <group
                name="mycar-wheelFtR_4"
                position={[1.401, 2.095, -0.526]}
                rotation={[Math.PI / 2, 0, 0]}
              >
                <mesh
                  name="Object_67"
                  geometry={nodes.Object_67.geometry}
                  material={materials["SCUDO_Yellow.003"]}
                  position={[-1.493, 0.525, 2.095]}
                />
                <mesh
                  name="Object_68"
                  geometry={nodes.Object_68.geometry}
                  material={materials["Red_METAL.003"]}
                />
                <mesh
                  name="Object_69"
                  geometry={nodes.Object_69.geometry}
                  material={materials["BRAKES_4K.003"]}
                />
                <mesh
                  name="Object_70"
                  geometry={nodes.Object_70.geometry}
                  material={materials["Black_Metal.003"]}
                />
                <mesh
                  name="Object_72"
                  geometry={nodes.Object_72.geometry}
                  material={materials["koplamp_binnen.004"]}
                />
                <mesh
                  name="Object_73"
                  geometry={nodes.Object_73.geometry}
                  material={materials["mclaren_logo.002"]}
                />
              </group>
            </group>
            <group
              name="DEF-WheelBrakeBkL_15"
              position={[1.346, 0.533, -4.715]}
              rotation={[-1.571, 0, 0]}
            >
              <group
                name="mycar-wheelbrakeBkL_14"
                position={[-1.346, -1.998, -0.533]}
                rotation={[Math.PI / 2, 0, 0]}
              >
                <mesh
                  name="Object_112"
                  geometry={nodes.Object_112.geometry}
                  material={materials["Brake_Pad.005"]}
                />
                <mesh
                  name="Object_113"
                  geometry={nodes.Object_113.geometry}
                  material={materials["Silver_METAL.005"]}
                />
                <mesh
                  name="Object_114"
                  geometry={nodes.Object_114.geometry}
                  material={materials["Brake_Disc_1.005"]}
                />
                <mesh
                  name="Object_115"
                  geometry={nodes.Object_115.geometry}
                  material={materials["Black_METAL.005"]}
                />
                <mesh
                  name="Object_116"
                  geometry={nodes.Object_116.geometry}
                  material={materials["Black_MATTE.005"]}
                />
                <mesh
                  name="Object_117"
                  geometry={nodes.Object_117.geometry}
                  material={materials["mini_brake.001"]}
                />
              </group>
            </group>
            <group
              name="DEF-WheelBrakeBkR_17"
              position={[-1.325, 0.533, -4.718]}
              rotation={[-1.571, 0, 0]}
            >
              <group
                name="mycar-wheelbrakeBkR_16"
                position={[1.325, -2.002, -0.533]}
                rotation={[Math.PI / 2, 0, 0]}
              >
                <mesh
                  name="Object_120"
                  geometry={nodes.Object_120.geometry}
                  material={materials["Brake_Pad.002"]}
                />
                <mesh
                  name="Object_121"
                  geometry={nodes.Object_121.geometry}
                  material={materials["Silver_METAL.002"]}
                />
                <mesh
                  name="Object_122"
                  geometry={nodes.Object_122.geometry}
                  material={materials["Brake_Disc_1.002"]}
                />
                <mesh
                  name="Object_123"
                  geometry={nodes.Object_123.geometry}
                  material={materials["Black_METAL.002"]}
                />
                <mesh
                  name="Object_124"
                  geometry={nodes.Object_124.geometry}
                  material={materials["Black_MATTE.002"]}
                />
                <mesh
                  name="Object_125"
                  geometry={nodes.Object_125.geometry}
                  material={materials.mini_brake}
                />
              </group>
            </group>
            <group
              name="DEF-WheelBrakeFtL_11"
              position={[1.323, 0.529, -0.784]}
              rotation={[-1.571, 0, 0]}
            >
              <group
                name="mycar-wheelbrakeFtL_10"
                position={[-1.323, 1.932, -0.528]}
                rotation={[Math.PI / 2, 0, 0]}
              >
                <mesh
                  name="Object_100"
                  geometry={nodes.Object_100.geometry}
                  material={materials["Brake_Disc_1.004"]}
                />
                <mesh
                  name="Object_101"
                  geometry={nodes.Object_101.geometry}
                  material={materials["Black_METAL.004"]}
                />
                <mesh
                  name="Object_102"
                  geometry={nodes.Object_102.geometry}
                  material={materials["Black_MATTE.004"]}
                />
                <mesh
                  name="Object_98"
                  geometry={nodes.Object_98.geometry}
                  material={materials["Brake_Pad.004"]}
                />
                <mesh
                  name="Object_99"
                  geometry={nodes.Object_99.geometry}
                  material={materials["Silver_METAL.004"]}
                />
              </group>
            </group>
            <group
              name="DEF-WheelBrakeFtR_13"
              position={[-1.344, 0.529, -0.793]}
              rotation={[-1.571, 0, 0]}
            >
              <group
                name="mycar-wheelbrakeFtR_12"
                position={[1.344, 1.924, -0.528]}
                rotation={[Math.PI / 2, 0, 0]}
              >
                <mesh
                  name="Object_105"
                  geometry={nodes.Object_105.geometry}
                  material={materials["Brake_Pad.003"]}
                />
                <mesh
                  name="Object_106"
                  geometry={nodes.Object_106.geometry}
                  material={materials["Silver_METAL.003"]}
                />
                <mesh
                  name="Object_107"
                  geometry={nodes.Object_107.geometry}
                  material={materials["Brake_Disc_1.003"]}
                />
                <mesh
                  name="Object_108"
                  geometry={nodes.Object_108.geometry}
                  material={materials["Black_METAL.003"]}
                />
                <mesh
                  name="Object_109"
                  geometry={nodes.Object_109.geometry}
                  material={materials["Black_MATTE.003"]}
                />
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/models/maclarn.glb");
